/*
 * Treezor
 * Treezor API.  more info [here](https://www.treezor.com). 
 *
 * OpenAPI spec version: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * TreezorMerchantIdRestrictionGroup
 */

public class TreezorMerchantIdRestrictionGroup {
  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("isWhitelist")
  private Boolean isWhitelist = null;

  @JsonProperty("merchants")
  private List<String> merchants = null;

  /**
   * status of the Merchant ID group
   */
  public enum StatusEnum {
    PENDING("PENDING"),
    
    CANCELED("CANCELED"),
    
    VALIDATED("VALIDATED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("status")
  private StatusEnum status = null;

  @JsonProperty("startDate")
  private String startDate = null;

  @JsonProperty("createdDate")
  private String createdDate = null;

  public TreezorMerchantIdRestrictionGroup id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Merchant ID Group&#39;s id
   * @return id
  **/
  @ApiModelProperty(value = "Merchant ID Group's id")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public TreezorMerchantIdRestrictionGroup name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Merchant ID Group&#39;s name
   * @return name
  **/
  @ApiModelProperty(value = "Merchant ID Group's name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TreezorMerchantIdRestrictionGroup isWhitelist(Boolean isWhitelist) {
    this.isWhitelist = isWhitelist;
    return this;
  }

   /**
   * determines whether it will be a black or a white list
   * @return isWhitelist
  **/
  @ApiModelProperty(value = "determines whether it will be a black or a white list")
  public Boolean isIsWhitelist() {
    return isWhitelist;
  }

  public void setIsWhitelist(Boolean isWhitelist) {
    this.isWhitelist = isWhitelist;
  }

  public TreezorMerchantIdRestrictionGroup merchants(List<String> merchants) {
    this.merchants = merchants;
    return this;
  }

  public TreezorMerchantIdRestrictionGroup addMerchantsItem(String merchantsItem) {
    if (this.merchants == null) {
      this.merchants = new ArrayList<>();
    }
    this.merchants.add(merchantsItem);
    return this;
  }

   /**
   * Array of Merchant ID
   * @return merchants
  **/
  @ApiModelProperty(value = "Array of Merchant ID")
  public List<String> getMerchants() {
    return merchants;
  }

  public void setMerchants(List<String> merchants) {
    this.merchants = merchants;
  }

  public TreezorMerchantIdRestrictionGroup status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * status of the Merchant ID group
   * @return status
  **/
  @ApiModelProperty(value = "status of the Merchant ID group")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public TreezorMerchantIdRestrictionGroup startDate(String startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Date YYYY-MM-DD HH:MM:SS
   * @return startDate
  **/
  @ApiModelProperty(value = "Date YYYY-MM-DD HH:MM:SS")
  public String getStartDate() {
    return startDate;
  }

  public void setStartDate(String startDate) {
    this.startDate = startDate;
  }

  public TreezorMerchantIdRestrictionGroup createdDate(String createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Date YYYY-MM-DD HH:MM:SS
   * @return createdDate
  **/
  @ApiModelProperty(value = "Date YYYY-MM-DD HH:MM:SS")
  public String getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(String createdDate) {
    this.createdDate = createdDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TreezorMerchantIdRestrictionGroup merchantIdRestrictionGroup = (TreezorMerchantIdRestrictionGroup) o;
    return Objects.equals(this.id, merchantIdRestrictionGroup.id) &&
        Objects.equals(this.name, merchantIdRestrictionGroup.name) &&
        Objects.equals(this.isWhitelist, merchantIdRestrictionGroup.isWhitelist) &&
        Objects.equals(this.merchants, merchantIdRestrictionGroup.merchants) &&
        Objects.equals(this.status, merchantIdRestrictionGroup.status) &&
        Objects.equals(this.startDate, merchantIdRestrictionGroup.startDate) &&
        Objects.equals(this.createdDate, merchantIdRestrictionGroup.createdDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, isWhitelist, merchants, status, startDate, createdDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TreezorMerchantIdRestrictionGroup {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    isWhitelist: ").append(toIndentedString(isWhitelist)).append("\n");
    sb.append("    merchants: ").append(toIndentedString(merchants)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

