/*
 * Treezor
 * Treezor API.  more info [here](https://www.treezor.com). 
 *
 * OpenAPI spec version: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * TreezorTaxResidence
 */

public class TreezorTaxResidence {
  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("userId")
  private Integer userId = null;

  @JsonProperty("country")
  private String country = null;

  @JsonProperty("taxPayerId")
  private String taxPayerId = null;

  @JsonProperty("liabilityWaiver")
  private Boolean liabilityWaiver = null;

  @JsonProperty("createdDate")
  private String createdDate = null;

  @JsonProperty("lastUpdate")
  private String lastUpdate = null;

  @JsonProperty("deletedDate")
  private String deletedDate = null;

  public TreezorTaxResidence id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * TaxResidence Id
   * @return id
  **/
  @ApiModelProperty(value = "TaxResidence Id")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public TreezorTaxResidence userId(Integer userId) {
    this.userId = userId;
    return this;
  }

   /**
   * The user id
   * @return userId
  **/
  @ApiModelProperty(value = "The user id")
  public Integer getUserId() {
    return userId;
  }

  public void setUserId(Integer userId) {
    this.userId = userId;
  }

  public TreezorTaxResidence country(String country) {
    this.country = country;
    return this;
  }

   /**
   * The residence country
   * @return country
  **/
  @ApiModelProperty(value = "The residence country")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public TreezorTaxResidence taxPayerId(String taxPayerId) {
    this.taxPayerId = taxPayerId;
    return this;
  }

   /**
   * the taxPayer id
   * @return taxPayerId
  **/
  @ApiModelProperty(value = "the taxPayer id")
  public String getTaxPayerId() {
    return taxPayerId;
  }

  public void setTaxPayerId(String taxPayerId) {
    this.taxPayerId = taxPayerId;
  }

  public TreezorTaxResidence liabilityWaiver(Boolean liabilityWaiver) {
    this.liabilityWaiver = liabilityWaiver;
    return this;
  }

   /**
   * Tax declaration
   * @return liabilityWaiver
  **/
  @ApiModelProperty(value = "Tax declaration")
  public Boolean isLiabilityWaiver() {
    return liabilityWaiver;
  }

  public void setLiabilityWaiver(Boolean liabilityWaiver) {
    this.liabilityWaiver = liabilityWaiver;
  }

  public TreezorTaxResidence createdDate(String createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Date of creation
   * @return createdDate
  **/
  @ApiModelProperty(value = "Date of creation")
  public String getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(String createdDate) {
    this.createdDate = createdDate;
  }

  public TreezorTaxResidence lastUpdate(String lastUpdate) {
    this.lastUpdate = lastUpdate;
    return this;
  }

   /**
   * Date of the TaxResidence has been updated
   * @return lastUpdate
  **/
  @ApiModelProperty(value = "Date of the TaxResidence has been updated")
  public String getLastUpdate() {
    return lastUpdate;
  }

  public void setLastUpdate(String lastUpdate) {
    this.lastUpdate = lastUpdate;
  }

  public TreezorTaxResidence deletedDate(String deletedDate) {
    this.deletedDate = deletedDate;
    return this;
  }

   /**
   * Date of the TaxResidence has been deleted
   * @return deletedDate
  **/
  @ApiModelProperty(value = "Date of the TaxResidence has been deleted")
  public String getDeletedDate() {
    return deletedDate;
  }

  public void setDeletedDate(String deletedDate) {
    this.deletedDate = deletedDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TreezorTaxResidence taxResidence = (TreezorTaxResidence) o;
    return Objects.equals(this.id, taxResidence.id) &&
        Objects.equals(this.userId, taxResidence.userId) &&
        Objects.equals(this.country, taxResidence.country) &&
        Objects.equals(this.taxPayerId, taxResidence.taxPayerId) &&
        Objects.equals(this.liabilityWaiver, taxResidence.liabilityWaiver) &&
        Objects.equals(this.createdDate, taxResidence.createdDate) &&
        Objects.equals(this.lastUpdate, taxResidence.lastUpdate) &&
        Objects.equals(this.deletedDate, taxResidence.deletedDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, userId, country, taxPayerId, liabilityWaiver, createdDate, lastUpdate, deletedDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TreezorTaxResidence {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    taxPayerId: ").append(toIndentedString(taxPayerId)).append("\n");
    sb.append("    liabilityWaiver: ").append(toIndentedString(liabilityWaiver)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    lastUpdate: ").append(toIndentedString(lastUpdate)).append("\n");
    sb.append("    deletedDate: ").append(toIndentedString(deletedDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

