/*
 * Treezor
 * Treezor API.  more info [here](https://www.treezor.com). 
 *
 * OpenAPI spec version: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

/**
 * TreezorInlineResponse2008
 */

public class TreezorInlineResponse2008 {
  @JsonProperty("cardId")
  private Long cardId = null;

  @JsonProperty("amount")
  private Float amount = null;

  @JsonProperty("calculationDate")
  private OffsetDateTime calculationDate = null;

  public TreezorInlineResponse2008 cardId(Long cardId) {
    this.cardId = cardId;
    return this;
  }

   /**
   * ID of the card
   * @return cardId
  **/
  @ApiModelProperty(value = "ID of the card")
  public Long getCardId() {
    return cardId;
  }

  public void setCardId(Long cardId) {
    this.cardId = cardId;
  }

  public TreezorInlineResponse2008 amount(Float amount) {
    this.amount = amount;
    return this;
  }

   /**
   * reserved amount of the card
   * @return amount
  **/
  @ApiModelProperty(value = "reserved amount of the card")
  public Float getAmount() {
    return amount;
  }

  public void setAmount(Float amount) {
    this.amount = amount;
  }

  public TreezorInlineResponse2008 calculationDate(OffsetDateTime calculationDate) {
    this.calculationDate = calculationDate;
    return this;
  }

   /**
   * last calculation date
   * @return calculationDate
  **/
  @ApiModelProperty(value = "last calculation date")
  public OffsetDateTime getCalculationDate() {
    return calculationDate;
  }

  public void setCalculationDate(OffsetDateTime calculationDate) {
    this.calculationDate = calculationDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TreezorInlineResponse2008 inlineResponse2008 = (TreezorInlineResponse2008) o;
    return Objects.equals(this.cardId, inlineResponse2008.cardId) &&
        Objects.equals(this.amount, inlineResponse2008.amount) &&
        Objects.equals(this.calculationDate, inlineResponse2008.calculationDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cardId, amount, calculationDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TreezorInlineResponse2008 {\n");
    
    sb.append("    cardId: ").append(toIndentedString(cardId)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    calculationDate: ").append(toIndentedString(calculationDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

