/*
 * Treezor
 * Treezor API.  more info [here](https://www.treezor.com). 
 *
 * OpenAPI spec version: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * TreezorTransferrefund
 */

public class TreezorTransferrefund {
  @JsonProperty("transferrefundId")
  private Integer transferrefundId = null;

  @JsonProperty("transferrefundTag")
  private String transferrefundTag = null;

  /**
   * Gets or Sets transferrefundStatus
   */
  public enum TransferrefundStatusEnum {
    PENDING("PENDING"),
    
    CANCELED("CANCELED"),
    
    VALIDATED("VALIDATED");

    private String value;

    TransferrefundStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TransferrefundStatusEnum fromValue(String text) {
      for (TransferrefundStatusEnum b : TransferrefundStatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("transferrefundStatus")
  private TransferrefundStatusEnum transferrefundStatus = null;

  @JsonProperty("codeStatus")
  private Integer codeStatus = null;

  @JsonProperty("informationStatus")
  private String informationStatus = null;

  @JsonProperty("walletId")
  private Integer walletId = null;

  @JsonProperty("transferId")
  private Integer transferId = null;

  @JsonProperty("transferrefundDate")
  private Integer transferrefundDate = null;

  @JsonProperty("amount")
  private String amount = null;

  @JsonProperty("currency")
  private String currency = null;

  @JsonProperty("createdDate")
  private String createdDate = null;

  @JsonProperty("modifiedDate")
  private String modifiedDate = null;

  @JsonProperty("totalRows")
  private Integer totalRows = null;

  public TreezorTransferrefund transferrefundId(Integer transferrefundId) {
    this.transferrefundId = transferrefundId;
    return this;
  }

   /**
   * Get transferrefundId
   * @return transferrefundId
  **/
  @ApiModelProperty(value = "")
  public Integer getTransferrefundId() {
    return transferrefundId;
  }

  public void setTransferrefundId(Integer transferrefundId) {
    this.transferrefundId = transferrefundId;
  }

  public TreezorTransferrefund transferrefundTag(String transferrefundTag) {
    this.transferrefundTag = transferrefundTag;
    return this;
  }

   /**
   * Get transferrefundTag
   * @return transferrefundTag
  **/
  @ApiModelProperty(value = "")
  public String getTransferrefundTag() {
    return transferrefundTag;
  }

  public void setTransferrefundTag(String transferrefundTag) {
    this.transferrefundTag = transferrefundTag;
  }

  public TreezorTransferrefund transferrefundStatus(TransferrefundStatusEnum transferrefundStatus) {
    this.transferrefundStatus = transferrefundStatus;
    return this;
  }

   /**
   * Get transferrefundStatus
   * @return transferrefundStatus
  **/
  @ApiModelProperty(value = "")
  public TransferrefundStatusEnum getTransferrefundStatus() {
    return transferrefundStatus;
  }

  public void setTransferrefundStatus(TransferrefundStatusEnum transferrefundStatus) {
    this.transferrefundStatus = transferrefundStatus;
  }

  public TreezorTransferrefund codeStatus(Integer codeStatus) {
    this.codeStatus = codeStatus;
    return this;
  }

   /**
   * Get codeStatus
   * @return codeStatus
  **/
  @ApiModelProperty(value = "")
  public Integer getCodeStatus() {
    return codeStatus;
  }

  public void setCodeStatus(Integer codeStatus) {
    this.codeStatus = codeStatus;
  }

  public TreezorTransferrefund informationStatus(String informationStatus) {
    this.informationStatus = informationStatus;
    return this;
  }

   /**
   * Get informationStatus
   * @return informationStatus
  **/
  @ApiModelProperty(value = "")
  public String getInformationStatus() {
    return informationStatus;
  }

  public void setInformationStatus(String informationStatus) {
    this.informationStatus = informationStatus;
  }

  public TreezorTransferrefund walletId(Integer walletId) {
    this.walletId = walletId;
    return this;
  }

   /**
   * Get walletId
   * @return walletId
  **/
  @ApiModelProperty(value = "")
  public Integer getWalletId() {
    return walletId;
  }

  public void setWalletId(Integer walletId) {
    this.walletId = walletId;
  }

  public TreezorTransferrefund transferId(Integer transferId) {
    this.transferId = transferId;
    return this;
  }

   /**
   * Get transferId
   * @return transferId
  **/
  @ApiModelProperty(value = "")
  public Integer getTransferId() {
    return transferId;
  }

  public void setTransferId(Integer transferId) {
    this.transferId = transferId;
  }

  public TreezorTransferrefund transferrefundDate(Integer transferrefundDate) {
    this.transferrefundDate = transferrefundDate;
    return this;
  }

   /**
   * Get transferrefundDate
   * @return transferrefundDate
  **/
  @ApiModelProperty(value = "")
  public Integer getTransferrefundDate() {
    return transferrefundDate;
  }

  public void setTransferrefundDate(Integer transferrefundDate) {
    this.transferrefundDate = transferrefundDate;
  }

  public TreezorTransferrefund amount(String amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @ApiModelProperty(value = "")
  public String getAmount() {
    return amount;
  }

  public void setAmount(String amount) {
    this.amount = amount;
  }

  public TreezorTransferrefund currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @ApiModelProperty(value = "")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public TreezorTransferrefund createdDate(String createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Date YYYY-MM-DD HH:MM:SS
   * @return createdDate
  **/
  @ApiModelProperty(value = "Date YYYY-MM-DD HH:MM:SS")
  public String getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(String createdDate) {
    this.createdDate = createdDate;
  }

  public TreezorTransferrefund modifiedDate(String modifiedDate) {
    this.modifiedDate = modifiedDate;
    return this;
  }

   /**
   * Date YYYY-MM-DD HH:MM:SS
   * @return modifiedDate
  **/
  @ApiModelProperty(value = "Date YYYY-MM-DD HH:MM:SS")
  public String getModifiedDate() {
    return modifiedDate;
  }

  public void setModifiedDate(String modifiedDate) {
    this.modifiedDate = modifiedDate;
  }

  public TreezorTransferrefund totalRows(Integer totalRows) {
    this.totalRows = totalRows;
    return this;
  }

   /**
   * Get totalRows
   * @return totalRows
  **/
  @ApiModelProperty(value = "")
  public Integer getTotalRows() {
    return totalRows;
  }

  public void setTotalRows(Integer totalRows) {
    this.totalRows = totalRows;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TreezorTransferrefund transferrefund = (TreezorTransferrefund) o;
    return Objects.equals(this.transferrefundId, transferrefund.transferrefundId) &&
        Objects.equals(this.transferrefundTag, transferrefund.transferrefundTag) &&
        Objects.equals(this.transferrefundStatus, transferrefund.transferrefundStatus) &&
        Objects.equals(this.codeStatus, transferrefund.codeStatus) &&
        Objects.equals(this.informationStatus, transferrefund.informationStatus) &&
        Objects.equals(this.walletId, transferrefund.walletId) &&
        Objects.equals(this.transferId, transferrefund.transferId) &&
        Objects.equals(this.transferrefundDate, transferrefund.transferrefundDate) &&
        Objects.equals(this.amount, transferrefund.amount) &&
        Objects.equals(this.currency, transferrefund.currency) &&
        Objects.equals(this.createdDate, transferrefund.createdDate) &&
        Objects.equals(this.modifiedDate, transferrefund.modifiedDate) &&
        Objects.equals(this.totalRows, transferrefund.totalRows);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transferrefundId, transferrefundTag, transferrefundStatus, codeStatus, informationStatus, walletId, transferId, transferrefundDate, amount, currency, createdDate, modifiedDate, totalRows);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TreezorTransferrefund {\n");
    
    sb.append("    transferrefundId: ").append(toIndentedString(transferrefundId)).append("\n");
    sb.append("    transferrefundTag: ").append(toIndentedString(transferrefundTag)).append("\n");
    sb.append("    transferrefundStatus: ").append(toIndentedString(transferrefundStatus)).append("\n");
    sb.append("    codeStatus: ").append(toIndentedString(codeStatus)).append("\n");
    sb.append("    informationStatus: ").append(toIndentedString(informationStatus)).append("\n");
    sb.append("    walletId: ").append(toIndentedString(walletId)).append("\n");
    sb.append("    transferId: ").append(toIndentedString(transferId)).append("\n");
    sb.append("    transferrefundDate: ").append(toIndentedString(transferrefundDate)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    modifiedDate: ").append(toIndentedString(modifiedDate)).append("\n");
    sb.append("    totalRows: ").append(toIndentedString(totalRows)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

