/*
 * Treezor
 * Treezor API.  more info [here](https://www.treezor.com). 
 *
 * OpenAPI spec version: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.TreezorPayinrefund;
import java.util.ArrayList;
import java.util.List;

/**
 * TreezorInlineResponse20018
 */

public class TreezorInlineResponse20018 {
  @JsonProperty("payinrefunds")
  private List<TreezorPayinrefund> payinrefunds = null;

  public TreezorInlineResponse20018 payinrefunds(List<TreezorPayinrefund> payinrefunds) {
    this.payinrefunds = payinrefunds;
    return this;
  }

  public TreezorInlineResponse20018 addPayinrefundsItem(TreezorPayinrefund payinrefundsItem) {
    if (this.payinrefunds == null) {
      this.payinrefunds = new ArrayList<>();
    }
    this.payinrefunds.add(payinrefundsItem);
    return this;
  }

   /**
   * Get payinrefunds
   * @return payinrefunds
  **/
  @ApiModelProperty(value = "")
  public List<TreezorPayinrefund> getPayinrefunds() {
    return payinrefunds;
  }

  public void setPayinrefunds(List<TreezorPayinrefund> payinrefunds) {
    this.payinrefunds = payinrefunds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TreezorInlineResponse20018 inlineResponse20018 = (TreezorInlineResponse20018) o;
    return Objects.equals(this.payinrefunds, inlineResponse20018.payinrefunds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(payinrefunds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TreezorInlineResponse20018 {\n");
    
    sb.append("    payinrefunds: ").append(toIndentedString(payinrefunds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

