/*
 * Treezor
 * Treezor API.  more info [here](https://www.treezor.com). 
 *
 * OpenAPI spec version: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.TreezorTransferrefund;
import java.util.ArrayList;
import java.util.List;

/**
 * TreezorInlineResponse20024
 */

public class TreezorInlineResponse20024 {
  @JsonProperty("transferrefunds")
  private List<TreezorTransferrefund> transferrefunds = null;

  public TreezorInlineResponse20024 transferrefunds(List<TreezorTransferrefund> transferrefunds) {
    this.transferrefunds = transferrefunds;
    return this;
  }

  public TreezorInlineResponse20024 addTransferrefundsItem(TreezorTransferrefund transferrefundsItem) {
    if (this.transferrefunds == null) {
      this.transferrefunds = new ArrayList<>();
    }
    this.transferrefunds.add(transferrefundsItem);
    return this;
  }

   /**
   * Get transferrefunds
   * @return transferrefunds
  **/
  @ApiModelProperty(value = "")
  public List<TreezorTransferrefund> getTransferrefunds() {
    return transferrefunds;
  }

  public void setTransferrefunds(List<TreezorTransferrefund> transferrefunds) {
    this.transferrefunds = transferrefunds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TreezorInlineResponse20024 inlineResponse20024 = (TreezorInlineResponse20024) o;
    return Objects.equals(this.transferrefunds, inlineResponse20024.transferrefunds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transferrefunds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TreezorInlineResponse20024 {\n");
    
    sb.append("    transferrefunds: ").append(toIndentedString(transferrefunds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

