/*
 * Treezor
 * Treezor API.  more info [here](https://www.treezor.com). 
 *
 * OpenAPI spec version: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.TreezorCard;
import java.util.ArrayList;
import java.util.List;

/**
 * TreezorInlineResponse2005
 */

public class TreezorInlineResponse2005 {
  @JsonProperty("cards")
  private List<TreezorCard> cards = null;

  public TreezorInlineResponse2005 cards(List<TreezorCard> cards) {
    this.cards = cards;
    return this;
  }

  public TreezorInlineResponse2005 addCardsItem(TreezorCard cardsItem) {
    if (this.cards == null) {
      this.cards = new ArrayList<>();
    }
    this.cards.add(cardsItem);
    return this;
  }

   /**
   * Get cards
   * @return cards
  **/
  @ApiModelProperty(value = "")
  public List<TreezorCard> getCards() {
    return cards;
  }

  public void setCards(List<TreezorCard> cards) {
    this.cards = cards;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TreezorInlineResponse2005 inlineResponse2005 = (TreezorInlineResponse2005) o;
    return Objects.equals(this.cards, inlineResponse2005.cards);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cards);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TreezorInlineResponse2005 {\n");
    
    sb.append("    cards: ").append(toIndentedString(cards)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

