/*
 * Treezor
 * Treezor API.  more info [here](https://www.treezor.com). 
 *
 * OpenAPI spec version: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.TreezorBeneficiary;
import java.util.ArrayList;
import java.util.List;

/**
 * TreezorInlineResponse2002
 */

public class TreezorInlineResponse2002 {
  @JsonProperty("beneficiaries")
  private List<TreezorBeneficiary> beneficiaries = null;

  public TreezorInlineResponse2002 beneficiaries(List<TreezorBeneficiary> beneficiaries) {
    this.beneficiaries = beneficiaries;
    return this;
  }

  public TreezorInlineResponse2002 addBeneficiariesItem(TreezorBeneficiary beneficiariesItem) {
    if (this.beneficiaries == null) {
      this.beneficiaries = new ArrayList<>();
    }
    this.beneficiaries.add(beneficiariesItem);
    return this;
  }

   /**
   * Get beneficiaries
   * @return beneficiaries
  **/
  @ApiModelProperty(value = "")
  public List<TreezorBeneficiary> getBeneficiaries() {
    return beneficiaries;
  }

  public void setBeneficiaries(List<TreezorBeneficiary> beneficiaries) {
    this.beneficiaries = beneficiaries;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TreezorInlineResponse2002 inlineResponse2002 = (TreezorInlineResponse2002) o;
    return Objects.equals(this.beneficiaries, inlineResponse2002.beneficiaries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(beneficiaries);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TreezorInlineResponse2002 {\n");
    
    sb.append("    beneficiaries: ").append(toIndentedString(beneficiaries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

