/*
 * Treezor
 * Treezor API.  more info [here](https://www.treezor.com). 
 *
 * OpenAPI spec version: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * TreezorInlineResponse2009Cardtransactions
 */

public class TreezorInlineResponse2009Cardtransactions {
  @JsonProperty("cardtransactionId")
  private Integer cardtransactionId = null;

  @JsonProperty("cardId")
  private Integer cardId = null;

  @JsonProperty("walletId")
  private Integer walletId = null;

  @JsonProperty("acquirerId")
  private Integer acquirerId = null;

  @JsonProperty("walletCurrency")
  private String walletCurrency = null;

  @JsonProperty("merchantId")
  private String merchantId = null;

  @JsonProperty("merchantName")
  private String merchantName = null;

  @JsonProperty("merchantCity")
  private String merchantCity = null;

  @JsonProperty("merchantCountry")
  private String merchantCountry = null;

  @JsonProperty("mccCode")
  private String mccCode = null;

  @JsonProperty("paymentLocalTime")
  private String paymentLocalTime = null;

  @JsonProperty("publicToken")
  private String publicToken = null;

  @JsonProperty("paymentAmount")
  private String paymentAmount = null;

  @JsonProperty("paymentCurrency")
  private String paymentCurrency = null;

  @JsonProperty("fees")
  private String fees = null;

  @JsonProperty("paymentCountry")
  private String paymentCountry = null;

  @JsonProperty("paymentId")
  private String paymentId = null;

  @JsonProperty("paymentStatus")
  private String paymentStatus = null;

  @JsonProperty("paymentLocalAmount")
  private String paymentLocalAmount = null;

  @JsonProperty("posCardholderPresence")
  private String posCardholderPresence = null;

  @JsonProperty("posPostcode")
  private String posPostcode = null;

  @JsonProperty("posCountry")
  private String posCountry = null;

  @JsonProperty("posTerminalId")
  private String posTerminalId = null;

  @JsonProperty("posCardPresence")
  private String posCardPresence = null;

  @JsonProperty("panEntryMethod")
  private String panEntryMethod = null;

  @JsonProperty("authorizationNote")
  private String authorizationNote = null;

  @JsonProperty("authorizationResponseCode")
  private String authorizationResponseCode = null;

  @JsonProperty("authorizationIssuerId")
  private String authorizationIssuerId = null;

  @JsonProperty("authorizationIssuerTime")
  private String authorizationIssuerTime = null;

  @JsonProperty("authorizationMti")
  private String authorizationMti = null;

  @JsonProperty("authorizedBalance")
  private String authorizedBalance = null;

  @JsonProperty("limitAtmYear")
  private String limitAtmYear = null;

  @JsonProperty("limitAtmMonth")
  private String limitAtmMonth = null;

  @JsonProperty("limitAtmWeek")
  private String limitAtmWeek = null;

  @JsonProperty("limitAtmDay")
  private String limitAtmDay = null;

  @JsonProperty("limitAtmAll")
  private String limitAtmAll = null;

  @JsonProperty("limitPaymentYear")
  private String limitPaymentYear = null;

  @JsonProperty("limitPaymentMonth")
  private String limitPaymentMonth = null;

  @JsonProperty("limitPaymentWeek")
  private String limitPaymentWeek = null;

  @JsonProperty("limitPaymentDay")
  private String limitPaymentDay = null;

  @JsonProperty("limitPaymentAll")
  private String limitPaymentAll = null;

  @JsonProperty("totalLimitAtmYear")
  private String totalLimitAtmYear = null;

  @JsonProperty("totalLimitAtmMonth")
  private String totalLimitAtmMonth = null;

  @JsonProperty("totalLimitAtmWeek")
  private String totalLimitAtmWeek = null;

  @JsonProperty("totalLimitAtmDay")
  private String totalLimitAtmDay = null;

  @JsonProperty("totalLimitAtmAll")
  private String totalLimitAtmAll = null;

  @JsonProperty("totalLimitPaymentYear")
  private String totalLimitPaymentYear = null;

  @JsonProperty("totalLimitPaymentMonth")
  private String totalLimitPaymentMonth = null;

  @JsonProperty("totalLimitPaymentWeek")
  private String totalLimitPaymentWeek = null;

  @JsonProperty("totalLimitPaymentDay")
  private String totalLimitPaymentDay = null;

  @JsonProperty("totalLimitPaymentAll")
  private String totalLimitPaymentAll = null;

  @JsonProperty("totalRows")
  private Integer totalRows = null;

  public TreezorInlineResponse2009Cardtransactions cardtransactionId(Integer cardtransactionId) {
    this.cardtransactionId = cardtransactionId;
    return this;
  }

   /**
   * Get cardtransactionId
   * @return cardtransactionId
  **/
  @ApiModelProperty(value = "")
  public Integer getCardtransactionId() {
    return cardtransactionId;
  }

  public void setCardtransactionId(Integer cardtransactionId) {
    this.cardtransactionId = cardtransactionId;
  }

  public TreezorInlineResponse2009Cardtransactions cardId(Integer cardId) {
    this.cardId = cardId;
    return this;
  }

   /**
   * Get cardId
   * @return cardId
  **/
  @ApiModelProperty(value = "")
  public Integer getCardId() {
    return cardId;
  }

  public void setCardId(Integer cardId) {
    this.cardId = cardId;
  }

  public TreezorInlineResponse2009Cardtransactions walletId(Integer walletId) {
    this.walletId = walletId;
    return this;
  }

   /**
   * Get walletId
   * @return walletId
  **/
  @ApiModelProperty(value = "")
  public Integer getWalletId() {
    return walletId;
  }

  public void setWalletId(Integer walletId) {
    this.walletId = walletId;
  }

  public TreezorInlineResponse2009Cardtransactions acquirerId(Integer acquirerId) {
    this.acquirerId = acquirerId;
    return this;
  }

   /**
   * Get acquirerId
   * @return acquirerId
  **/
  @ApiModelProperty(value = "")
  public Integer getAcquirerId() {
    return acquirerId;
  }

  public void setAcquirerId(Integer acquirerId) {
    this.acquirerId = acquirerId;
  }

  public TreezorInlineResponse2009Cardtransactions walletCurrency(String walletCurrency) {
    this.walletCurrency = walletCurrency;
    return this;
  }

   /**
   * Get walletCurrency
   * @return walletCurrency
  **/
  @ApiModelProperty(value = "")
  public String getWalletCurrency() {
    return walletCurrency;
  }

  public void setWalletCurrency(String walletCurrency) {
    this.walletCurrency = walletCurrency;
  }

  public TreezorInlineResponse2009Cardtransactions merchantId(String merchantId) {
    this.merchantId = merchantId;
    return this;
  }

   /**
   * Get merchantId
   * @return merchantId
  **/
  @ApiModelProperty(value = "")
  public String getMerchantId() {
    return merchantId;
  }

  public void setMerchantId(String merchantId) {
    this.merchantId = merchantId;
  }

  public TreezorInlineResponse2009Cardtransactions merchantName(String merchantName) {
    this.merchantName = merchantName;
    return this;
  }

   /**
   * Get merchantName
   * @return merchantName
  **/
  @ApiModelProperty(value = "")
  public String getMerchantName() {
    return merchantName;
  }

  public void setMerchantName(String merchantName) {
    this.merchantName = merchantName;
  }

  public TreezorInlineResponse2009Cardtransactions merchantCity(String merchantCity) {
    this.merchantCity = merchantCity;
    return this;
  }

   /**
   * Get merchantCity
   * @return merchantCity
  **/
  @ApiModelProperty(value = "")
  public String getMerchantCity() {
    return merchantCity;
  }

  public void setMerchantCity(String merchantCity) {
    this.merchantCity = merchantCity;
  }

  public TreezorInlineResponse2009Cardtransactions merchantCountry(String merchantCountry) {
    this.merchantCountry = merchantCountry;
    return this;
  }

   /**
   * Get merchantCountry
   * @return merchantCountry
  **/
  @ApiModelProperty(value = "")
  public String getMerchantCountry() {
    return merchantCountry;
  }

  public void setMerchantCountry(String merchantCountry) {
    this.merchantCountry = merchantCountry;
  }

  public TreezorInlineResponse2009Cardtransactions mccCode(String mccCode) {
    this.mccCode = mccCode;
    return this;
  }

   /**
   * Get mccCode
   * @return mccCode
  **/
  @ApiModelProperty(value = "")
  public String getMccCode() {
    return mccCode;
  }

  public void setMccCode(String mccCode) {
    this.mccCode = mccCode;
  }

  public TreezorInlineResponse2009Cardtransactions paymentLocalTime(String paymentLocalTime) {
    this.paymentLocalTime = paymentLocalTime;
    return this;
  }

   /**
   * Get paymentLocalTime
   * @return paymentLocalTime
  **/
  @ApiModelProperty(value = "")
  public String getPaymentLocalTime() {
    return paymentLocalTime;
  }

  public void setPaymentLocalTime(String paymentLocalTime) {
    this.paymentLocalTime = paymentLocalTime;
  }

  public TreezorInlineResponse2009Cardtransactions publicToken(String publicToken) {
    this.publicToken = publicToken;
    return this;
  }

   /**
   * Get publicToken
   * @return publicToken
  **/
  @ApiModelProperty(value = "")
  public String getPublicToken() {
    return publicToken;
  }

  public void setPublicToken(String publicToken) {
    this.publicToken = publicToken;
  }

  public TreezorInlineResponse2009Cardtransactions paymentAmount(String paymentAmount) {
    this.paymentAmount = paymentAmount;
    return this;
  }

   /**
   * Get paymentAmount
   * @return paymentAmount
  **/
  @ApiModelProperty(value = "")
  public String getPaymentAmount() {
    return paymentAmount;
  }

  public void setPaymentAmount(String paymentAmount) {
    this.paymentAmount = paymentAmount;
  }

  public TreezorInlineResponse2009Cardtransactions paymentCurrency(String paymentCurrency) {
    this.paymentCurrency = paymentCurrency;
    return this;
  }

   /**
   * payment currency. Format: [ISO 4217](https://fr.wikipedia.org/wiki/ISO_4217). 
   * @return paymentCurrency
  **/
  @ApiModelProperty(value = "payment currency. Format: [ISO 4217](https://fr.wikipedia.org/wiki/ISO_4217). ")
  public String getPaymentCurrency() {
    return paymentCurrency;
  }

  public void setPaymentCurrency(String paymentCurrency) {
    this.paymentCurrency = paymentCurrency;
  }

  public TreezorInlineResponse2009Cardtransactions fees(String fees) {
    this.fees = fees;
    return this;
  }

   /**
   * Get fees
   * @return fees
  **/
  @ApiModelProperty(value = "")
  public String getFees() {
    return fees;
  }

  public void setFees(String fees) {
    this.fees = fees;
  }

  public TreezorInlineResponse2009Cardtransactions paymentCountry(String paymentCountry) {
    this.paymentCountry = paymentCountry;
    return this;
  }

   /**
   * Get paymentCountry
   * @return paymentCountry
  **/
  @ApiModelProperty(value = "")
  public String getPaymentCountry() {
    return paymentCountry;
  }

  public void setPaymentCountry(String paymentCountry) {
    this.paymentCountry = paymentCountry;
  }

  public TreezorInlineResponse2009Cardtransactions paymentId(String paymentId) {
    this.paymentId = paymentId;
    return this;
  }

   /**
   * Get paymentId
   * @return paymentId
  **/
  @ApiModelProperty(value = "")
  public String getPaymentId() {
    return paymentId;
  }

  public void setPaymentId(String paymentId) {
    this.paymentId = paymentId;
  }

  public TreezorInlineResponse2009Cardtransactions paymentStatus(String paymentStatus) {
    this.paymentStatus = paymentStatus;
    return this;
  }

   /**
   * Payment status.  | Status | Description | | ------ | -------     | | A | Accepted | | C | Cleared | | I | Declined | | S | Settled | | V | Reversed | 
   * @return paymentStatus
  **/
  @ApiModelProperty(value = "Payment status.  | Status | Description | | ------ | -------     | | A | Accepted | | C | Cleared | | I | Declined | | S | Settled | | V | Reversed | ")
  public String getPaymentStatus() {
    return paymentStatus;
  }

  public void setPaymentStatus(String paymentStatus) {
    this.paymentStatus = paymentStatus;
  }

  public TreezorInlineResponse2009Cardtransactions paymentLocalAmount(String paymentLocalAmount) {
    this.paymentLocalAmount = paymentLocalAmount;
    return this;
  }

   /**
   * Get paymentLocalAmount
   * @return paymentLocalAmount
  **/
  @ApiModelProperty(value = "")
  public String getPaymentLocalAmount() {
    return paymentLocalAmount;
  }

  public void setPaymentLocalAmount(String paymentLocalAmount) {
    this.paymentLocalAmount = paymentLocalAmount;
  }

  public TreezorInlineResponse2009Cardtransactions posCardholderPresence(String posCardholderPresence) {
    this.posCardholderPresence = posCardholderPresence;
    return this;
  }

   /**
   * Get posCardholderPresence
   * @return posCardholderPresence
  **/
  @ApiModelProperty(value = "")
  public String getPosCardholderPresence() {
    return posCardholderPresence;
  }

  public void setPosCardholderPresence(String posCardholderPresence) {
    this.posCardholderPresence = posCardholderPresence;
  }

  public TreezorInlineResponse2009Cardtransactions posPostcode(String posPostcode) {
    this.posPostcode = posPostcode;
    return this;
  }

   /**
   * Get posPostcode
   * @return posPostcode
  **/
  @ApiModelProperty(value = "")
  public String getPosPostcode() {
    return posPostcode;
  }

  public void setPosPostcode(String posPostcode) {
    this.posPostcode = posPostcode;
  }

  public TreezorInlineResponse2009Cardtransactions posCountry(String posCountry) {
    this.posCountry = posCountry;
    return this;
  }

   /**
   * Get posCountry
   * @return posCountry
  **/
  @ApiModelProperty(value = "")
  public String getPosCountry() {
    return posCountry;
  }

  public void setPosCountry(String posCountry) {
    this.posCountry = posCountry;
  }

  public TreezorInlineResponse2009Cardtransactions posTerminalId(String posTerminalId) {
    this.posTerminalId = posTerminalId;
    return this;
  }

   /**
   * Get posTerminalId
   * @return posTerminalId
  **/
  @ApiModelProperty(value = "")
  public String getPosTerminalId() {
    return posTerminalId;
  }

  public void setPosTerminalId(String posTerminalId) {
    this.posTerminalId = posTerminalId;
  }

  public TreezorInlineResponse2009Cardtransactions posCardPresence(String posCardPresence) {
    this.posCardPresence = posCardPresence;
    return this;
  }

   /**
   * Get posCardPresence
   * @return posCardPresence
  **/
  @ApiModelProperty(value = "")
  public String getPosCardPresence() {
    return posCardPresence;
  }

  public void setPosCardPresence(String posCardPresence) {
    this.posCardPresence = posCardPresence;
  }

  public TreezorInlineResponse2009Cardtransactions panEntryMethod(String panEntryMethod) {
    this.panEntryMethod = panEntryMethod;
    return this;
  }

   /**
   * Get panEntryMethod
   * @return panEntryMethod
  **/
  @ApiModelProperty(value = "")
  public String getPanEntryMethod() {
    return panEntryMethod;
  }

  public void setPanEntryMethod(String panEntryMethod) {
    this.panEntryMethod = panEntryMethod;
  }

  public TreezorInlineResponse2009Cardtransactions authorizationNote(String authorizationNote) {
    this.authorizationNote = authorizationNote;
    return this;
  }

   /**
   * Get authorizationNote
   * @return authorizationNote
  **/
  @ApiModelProperty(value = "")
  public String getAuthorizationNote() {
    return authorizationNote;
  }

  public void setAuthorizationNote(String authorizationNote) {
    this.authorizationNote = authorizationNote;
  }

  public TreezorInlineResponse2009Cardtransactions authorizationResponseCode(String authorizationResponseCode) {
    this.authorizationResponseCode = authorizationResponseCode;
    return this;
  }

   /**
   * Authorization response code.  | Code | Description | | ---- | ----------- | | 00 | All Good | | 01 | Refer to card issuer Refer | | 03 | Invalid merchant Decline | | 05 | Do not honour Decline | | 10 | Partial Approval Approve | | 13 | Invalid amount Decline | | 14 | Invalid card number (no such number) Decline | | 17 | Customer Cancellation Decline | | 33 | Expired card (Capture) Decline &amp; Pickup | | 41 | Lost card (Capture) Decline &amp; Pickup | | 43 | Stolen card (Capture) Decline &amp; Pickup | | 51 | Insufficient funds Decline | | 54 | Expired card Decline | | 55 | Incorrect PIN Decline | | 57 | Transaction not permitted to cardholder Decline | | 58 | Transaction not permitted to terminal Decline | | 61 | Exceeds withdrawal amount limit Decline | | 62 | Restricted card Decline | | 63 | Security Violation Decline | | 65 | Exceeds withdrawal frequency limit Decline | | 68 | Response received too late Decline | | 70 | Cardholder to contact issuer Decline | | 75 | Allowable number of PIN tries exceeded Decline | | 82 | Timeout at IEM Decline | | 85 | PIN Unblock request Approve | | 91 | Issuer or switch is inoperative Decline | | N7 | Decline for CVV2 failure Decline | 
   * @return authorizationResponseCode
  **/
  @ApiModelProperty(value = "Authorization response code.  | Code | Description | | ---- | ----------- | | 00 | All Good | | 01 | Refer to card issuer Refer | | 03 | Invalid merchant Decline | | 05 | Do not honour Decline | | 10 | Partial Approval Approve | | 13 | Invalid amount Decline | | 14 | Invalid card number (no such number) Decline | | 17 | Customer Cancellation Decline | | 33 | Expired card (Capture) Decline & Pickup | | 41 | Lost card (Capture) Decline & Pickup | | 43 | Stolen card (Capture) Decline & Pickup | | 51 | Insufficient funds Decline | | 54 | Expired card Decline | | 55 | Incorrect PIN Decline | | 57 | Transaction not permitted to cardholder Decline | | 58 | Transaction not permitted to terminal Decline | | 61 | Exceeds withdrawal amount limit Decline | | 62 | Restricted card Decline | | 63 | Security Violation Decline | | 65 | Exceeds withdrawal frequency limit Decline | | 68 | Response received too late Decline | | 70 | Cardholder to contact issuer Decline | | 75 | Allowable number of PIN tries exceeded Decline | | 82 | Timeout at IEM Decline | | 85 | PIN Unblock request Approve | | 91 | Issuer or switch is inoperative Decline | | N7 | Decline for CVV2 failure Decline | ")
  public String getAuthorizationResponseCode() {
    return authorizationResponseCode;
  }

  public void setAuthorizationResponseCode(String authorizationResponseCode) {
    this.authorizationResponseCode = authorizationResponseCode;
  }

  public TreezorInlineResponse2009Cardtransactions authorizationIssuerId(String authorizationIssuerId) {
    this.authorizationIssuerId = authorizationIssuerId;
    return this;
  }

   /**
   * Get authorizationIssuerId
   * @return authorizationIssuerId
  **/
  @ApiModelProperty(value = "")
  public String getAuthorizationIssuerId() {
    return authorizationIssuerId;
  }

  public void setAuthorizationIssuerId(String authorizationIssuerId) {
    this.authorizationIssuerId = authorizationIssuerId;
  }

  public TreezorInlineResponse2009Cardtransactions authorizationIssuerTime(String authorizationIssuerTime) {
    this.authorizationIssuerTime = authorizationIssuerTime;
    return this;
  }

   /**
   * Get authorizationIssuerTime
   * @return authorizationIssuerTime
  **/
  @ApiModelProperty(value = "")
  public String getAuthorizationIssuerTime() {
    return authorizationIssuerTime;
  }

  public void setAuthorizationIssuerTime(String authorizationIssuerTime) {
    this.authorizationIssuerTime = authorizationIssuerTime;
  }

  public TreezorInlineResponse2009Cardtransactions authorizationMti(String authorizationMti) {
    this.authorizationMti = authorizationMti;
    return this;
  }

   /**
   * Authorization Message Type Identifier  | MTI | Description | | --- | ----| | 01xx | Authorization message | | 04xx | reversal message | | 12xx | Financial message | 
   * @return authorizationMti
  **/
  @ApiModelProperty(value = "Authorization Message Type Identifier  | MTI | Description | | --- | ----| | 01xx | Authorization message | | 04xx | reversal message | | 12xx | Financial message | ")
  public String getAuthorizationMti() {
    return authorizationMti;
  }

  public void setAuthorizationMti(String authorizationMti) {
    this.authorizationMti = authorizationMti;
  }

  public TreezorInlineResponse2009Cardtransactions authorizedBalance(String authorizedBalance) {
    this.authorizedBalance = authorizedBalance;
    return this;
  }

   /**
   * Get authorizedBalance
   * @return authorizedBalance
  **/
  @ApiModelProperty(value = "")
  public String getAuthorizedBalance() {
    return authorizedBalance;
  }

  public void setAuthorizedBalance(String authorizedBalance) {
    this.authorizedBalance = authorizedBalance;
  }

  public TreezorInlineResponse2009Cardtransactions limitAtmYear(String limitAtmYear) {
    this.limitAtmYear = limitAtmYear;
    return this;
  }

   /**
   * Get limitAtmYear
   * @return limitAtmYear
  **/
  @ApiModelProperty(value = "")
  public String getLimitAtmYear() {
    return limitAtmYear;
  }

  public void setLimitAtmYear(String limitAtmYear) {
    this.limitAtmYear = limitAtmYear;
  }

  public TreezorInlineResponse2009Cardtransactions limitAtmMonth(String limitAtmMonth) {
    this.limitAtmMonth = limitAtmMonth;
    return this;
  }

   /**
   * Get limitAtmMonth
   * @return limitAtmMonth
  **/
  @ApiModelProperty(value = "")
  public String getLimitAtmMonth() {
    return limitAtmMonth;
  }

  public void setLimitAtmMonth(String limitAtmMonth) {
    this.limitAtmMonth = limitAtmMonth;
  }

  public TreezorInlineResponse2009Cardtransactions limitAtmWeek(String limitAtmWeek) {
    this.limitAtmWeek = limitAtmWeek;
    return this;
  }

   /**
   * Get limitAtmWeek
   * @return limitAtmWeek
  **/
  @ApiModelProperty(value = "")
  public String getLimitAtmWeek() {
    return limitAtmWeek;
  }

  public void setLimitAtmWeek(String limitAtmWeek) {
    this.limitAtmWeek = limitAtmWeek;
  }

  public TreezorInlineResponse2009Cardtransactions limitAtmDay(String limitAtmDay) {
    this.limitAtmDay = limitAtmDay;
    return this;
  }

   /**
   * Get limitAtmDay
   * @return limitAtmDay
  **/
  @ApiModelProperty(value = "")
  public String getLimitAtmDay() {
    return limitAtmDay;
  }

  public void setLimitAtmDay(String limitAtmDay) {
    this.limitAtmDay = limitAtmDay;
  }

  public TreezorInlineResponse2009Cardtransactions limitAtmAll(String limitAtmAll) {
    this.limitAtmAll = limitAtmAll;
    return this;
  }

   /**
   * Get limitAtmAll
   * @return limitAtmAll
  **/
  @ApiModelProperty(value = "")
  public String getLimitAtmAll() {
    return limitAtmAll;
  }

  public void setLimitAtmAll(String limitAtmAll) {
    this.limitAtmAll = limitAtmAll;
  }

  public TreezorInlineResponse2009Cardtransactions limitPaymentYear(String limitPaymentYear) {
    this.limitPaymentYear = limitPaymentYear;
    return this;
  }

   /**
   * Get limitPaymentYear
   * @return limitPaymentYear
  **/
  @ApiModelProperty(value = "")
  public String getLimitPaymentYear() {
    return limitPaymentYear;
  }

  public void setLimitPaymentYear(String limitPaymentYear) {
    this.limitPaymentYear = limitPaymentYear;
  }

  public TreezorInlineResponse2009Cardtransactions limitPaymentMonth(String limitPaymentMonth) {
    this.limitPaymentMonth = limitPaymentMonth;
    return this;
  }

   /**
   * Get limitPaymentMonth
   * @return limitPaymentMonth
  **/
  @ApiModelProperty(value = "")
  public String getLimitPaymentMonth() {
    return limitPaymentMonth;
  }

  public void setLimitPaymentMonth(String limitPaymentMonth) {
    this.limitPaymentMonth = limitPaymentMonth;
  }

  public TreezorInlineResponse2009Cardtransactions limitPaymentWeek(String limitPaymentWeek) {
    this.limitPaymentWeek = limitPaymentWeek;
    return this;
  }

   /**
   * Get limitPaymentWeek
   * @return limitPaymentWeek
  **/
  @ApiModelProperty(value = "")
  public String getLimitPaymentWeek() {
    return limitPaymentWeek;
  }

  public void setLimitPaymentWeek(String limitPaymentWeek) {
    this.limitPaymentWeek = limitPaymentWeek;
  }

  public TreezorInlineResponse2009Cardtransactions limitPaymentDay(String limitPaymentDay) {
    this.limitPaymentDay = limitPaymentDay;
    return this;
  }

   /**
   * Get limitPaymentDay
   * @return limitPaymentDay
  **/
  @ApiModelProperty(value = "")
  public String getLimitPaymentDay() {
    return limitPaymentDay;
  }

  public void setLimitPaymentDay(String limitPaymentDay) {
    this.limitPaymentDay = limitPaymentDay;
  }

  public TreezorInlineResponse2009Cardtransactions limitPaymentAll(String limitPaymentAll) {
    this.limitPaymentAll = limitPaymentAll;
    return this;
  }

   /**
   * Get limitPaymentAll
   * @return limitPaymentAll
  **/
  @ApiModelProperty(value = "")
  public String getLimitPaymentAll() {
    return limitPaymentAll;
  }

  public void setLimitPaymentAll(String limitPaymentAll) {
    this.limitPaymentAll = limitPaymentAll;
  }

  public TreezorInlineResponse2009Cardtransactions totalLimitAtmYear(String totalLimitAtmYear) {
    this.totalLimitAtmYear = totalLimitAtmYear;
    return this;
  }

   /**
   * Get totalLimitAtmYear
   * @return totalLimitAtmYear
  **/
  @ApiModelProperty(value = "")
  public String getTotalLimitAtmYear() {
    return totalLimitAtmYear;
  }

  public void setTotalLimitAtmYear(String totalLimitAtmYear) {
    this.totalLimitAtmYear = totalLimitAtmYear;
  }

  public TreezorInlineResponse2009Cardtransactions totalLimitAtmMonth(String totalLimitAtmMonth) {
    this.totalLimitAtmMonth = totalLimitAtmMonth;
    return this;
  }

   /**
   * Get totalLimitAtmMonth
   * @return totalLimitAtmMonth
  **/
  @ApiModelProperty(value = "")
  public String getTotalLimitAtmMonth() {
    return totalLimitAtmMonth;
  }

  public void setTotalLimitAtmMonth(String totalLimitAtmMonth) {
    this.totalLimitAtmMonth = totalLimitAtmMonth;
  }

  public TreezorInlineResponse2009Cardtransactions totalLimitAtmWeek(String totalLimitAtmWeek) {
    this.totalLimitAtmWeek = totalLimitAtmWeek;
    return this;
  }

   /**
   * Get totalLimitAtmWeek
   * @return totalLimitAtmWeek
  **/
  @ApiModelProperty(value = "")
  public String getTotalLimitAtmWeek() {
    return totalLimitAtmWeek;
  }

  public void setTotalLimitAtmWeek(String totalLimitAtmWeek) {
    this.totalLimitAtmWeek = totalLimitAtmWeek;
  }

  public TreezorInlineResponse2009Cardtransactions totalLimitAtmDay(String totalLimitAtmDay) {
    this.totalLimitAtmDay = totalLimitAtmDay;
    return this;
  }

   /**
   * Get totalLimitAtmDay
   * @return totalLimitAtmDay
  **/
  @ApiModelProperty(value = "")
  public String getTotalLimitAtmDay() {
    return totalLimitAtmDay;
  }

  public void setTotalLimitAtmDay(String totalLimitAtmDay) {
    this.totalLimitAtmDay = totalLimitAtmDay;
  }

  public TreezorInlineResponse2009Cardtransactions totalLimitAtmAll(String totalLimitAtmAll) {
    this.totalLimitAtmAll = totalLimitAtmAll;
    return this;
  }

   /**
   * Get totalLimitAtmAll
   * @return totalLimitAtmAll
  **/
  @ApiModelProperty(value = "")
  public String getTotalLimitAtmAll() {
    return totalLimitAtmAll;
  }

  public void setTotalLimitAtmAll(String totalLimitAtmAll) {
    this.totalLimitAtmAll = totalLimitAtmAll;
  }

  public TreezorInlineResponse2009Cardtransactions totalLimitPaymentYear(String totalLimitPaymentYear) {
    this.totalLimitPaymentYear = totalLimitPaymentYear;
    return this;
  }

   /**
   * Get totalLimitPaymentYear
   * @return totalLimitPaymentYear
  **/
  @ApiModelProperty(value = "")
  public String getTotalLimitPaymentYear() {
    return totalLimitPaymentYear;
  }

  public void setTotalLimitPaymentYear(String totalLimitPaymentYear) {
    this.totalLimitPaymentYear = totalLimitPaymentYear;
  }

  public TreezorInlineResponse2009Cardtransactions totalLimitPaymentMonth(String totalLimitPaymentMonth) {
    this.totalLimitPaymentMonth = totalLimitPaymentMonth;
    return this;
  }

   /**
   * Get totalLimitPaymentMonth
   * @return totalLimitPaymentMonth
  **/
  @ApiModelProperty(value = "")
  public String getTotalLimitPaymentMonth() {
    return totalLimitPaymentMonth;
  }

  public void setTotalLimitPaymentMonth(String totalLimitPaymentMonth) {
    this.totalLimitPaymentMonth = totalLimitPaymentMonth;
  }

  public TreezorInlineResponse2009Cardtransactions totalLimitPaymentWeek(String totalLimitPaymentWeek) {
    this.totalLimitPaymentWeek = totalLimitPaymentWeek;
    return this;
  }

   /**
   * Get totalLimitPaymentWeek
   * @return totalLimitPaymentWeek
  **/
  @ApiModelProperty(value = "")
  public String getTotalLimitPaymentWeek() {
    return totalLimitPaymentWeek;
  }

  public void setTotalLimitPaymentWeek(String totalLimitPaymentWeek) {
    this.totalLimitPaymentWeek = totalLimitPaymentWeek;
  }

  public TreezorInlineResponse2009Cardtransactions totalLimitPaymentDay(String totalLimitPaymentDay) {
    this.totalLimitPaymentDay = totalLimitPaymentDay;
    return this;
  }

   /**
   * Get totalLimitPaymentDay
   * @return totalLimitPaymentDay
  **/
  @ApiModelProperty(value = "")
  public String getTotalLimitPaymentDay() {
    return totalLimitPaymentDay;
  }

  public void setTotalLimitPaymentDay(String totalLimitPaymentDay) {
    this.totalLimitPaymentDay = totalLimitPaymentDay;
  }

  public TreezorInlineResponse2009Cardtransactions totalLimitPaymentAll(String totalLimitPaymentAll) {
    this.totalLimitPaymentAll = totalLimitPaymentAll;
    return this;
  }

   /**
   * Get totalLimitPaymentAll
   * @return totalLimitPaymentAll
  **/
  @ApiModelProperty(value = "")
  public String getTotalLimitPaymentAll() {
    return totalLimitPaymentAll;
  }

  public void setTotalLimitPaymentAll(String totalLimitPaymentAll) {
    this.totalLimitPaymentAll = totalLimitPaymentAll;
  }

  public TreezorInlineResponse2009Cardtransactions totalRows(Integer totalRows) {
    this.totalRows = totalRows;
    return this;
  }

   /**
   * Get totalRows
   * @return totalRows
  **/
  @ApiModelProperty(value = "")
  public Integer getTotalRows() {
    return totalRows;
  }

  public void setTotalRows(Integer totalRows) {
    this.totalRows = totalRows;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TreezorInlineResponse2009Cardtransactions inlineResponse2009Cardtransactions = (TreezorInlineResponse2009Cardtransactions) o;
    return Objects.equals(this.cardtransactionId, inlineResponse2009Cardtransactions.cardtransactionId) &&
        Objects.equals(this.cardId, inlineResponse2009Cardtransactions.cardId) &&
        Objects.equals(this.walletId, inlineResponse2009Cardtransactions.walletId) &&
        Objects.equals(this.acquirerId, inlineResponse2009Cardtransactions.acquirerId) &&
        Objects.equals(this.walletCurrency, inlineResponse2009Cardtransactions.walletCurrency) &&
        Objects.equals(this.merchantId, inlineResponse2009Cardtransactions.merchantId) &&
        Objects.equals(this.merchantName, inlineResponse2009Cardtransactions.merchantName) &&
        Objects.equals(this.merchantCity, inlineResponse2009Cardtransactions.merchantCity) &&
        Objects.equals(this.merchantCountry, inlineResponse2009Cardtransactions.merchantCountry) &&
        Objects.equals(this.mccCode, inlineResponse2009Cardtransactions.mccCode) &&
        Objects.equals(this.paymentLocalTime, inlineResponse2009Cardtransactions.paymentLocalTime) &&
        Objects.equals(this.publicToken, inlineResponse2009Cardtransactions.publicToken) &&
        Objects.equals(this.paymentAmount, inlineResponse2009Cardtransactions.paymentAmount) &&
        Objects.equals(this.paymentCurrency, inlineResponse2009Cardtransactions.paymentCurrency) &&
        Objects.equals(this.fees, inlineResponse2009Cardtransactions.fees) &&
        Objects.equals(this.paymentCountry, inlineResponse2009Cardtransactions.paymentCountry) &&
        Objects.equals(this.paymentId, inlineResponse2009Cardtransactions.paymentId) &&
        Objects.equals(this.paymentStatus, inlineResponse2009Cardtransactions.paymentStatus) &&
        Objects.equals(this.paymentLocalAmount, inlineResponse2009Cardtransactions.paymentLocalAmount) &&
        Objects.equals(this.posCardholderPresence, inlineResponse2009Cardtransactions.posCardholderPresence) &&
        Objects.equals(this.posPostcode, inlineResponse2009Cardtransactions.posPostcode) &&
        Objects.equals(this.posCountry, inlineResponse2009Cardtransactions.posCountry) &&
        Objects.equals(this.posTerminalId, inlineResponse2009Cardtransactions.posTerminalId) &&
        Objects.equals(this.posCardPresence, inlineResponse2009Cardtransactions.posCardPresence) &&
        Objects.equals(this.panEntryMethod, inlineResponse2009Cardtransactions.panEntryMethod) &&
        Objects.equals(this.authorizationNote, inlineResponse2009Cardtransactions.authorizationNote) &&
        Objects.equals(this.authorizationResponseCode, inlineResponse2009Cardtransactions.authorizationResponseCode) &&
        Objects.equals(this.authorizationIssuerId, inlineResponse2009Cardtransactions.authorizationIssuerId) &&
        Objects.equals(this.authorizationIssuerTime, inlineResponse2009Cardtransactions.authorizationIssuerTime) &&
        Objects.equals(this.authorizationMti, inlineResponse2009Cardtransactions.authorizationMti) &&
        Objects.equals(this.authorizedBalance, inlineResponse2009Cardtransactions.authorizedBalance) &&
        Objects.equals(this.limitAtmYear, inlineResponse2009Cardtransactions.limitAtmYear) &&
        Objects.equals(this.limitAtmMonth, inlineResponse2009Cardtransactions.limitAtmMonth) &&
        Objects.equals(this.limitAtmWeek, inlineResponse2009Cardtransactions.limitAtmWeek) &&
        Objects.equals(this.limitAtmDay, inlineResponse2009Cardtransactions.limitAtmDay) &&
        Objects.equals(this.limitAtmAll, inlineResponse2009Cardtransactions.limitAtmAll) &&
        Objects.equals(this.limitPaymentYear, inlineResponse2009Cardtransactions.limitPaymentYear) &&
        Objects.equals(this.limitPaymentMonth, inlineResponse2009Cardtransactions.limitPaymentMonth) &&
        Objects.equals(this.limitPaymentWeek, inlineResponse2009Cardtransactions.limitPaymentWeek) &&
        Objects.equals(this.limitPaymentDay, inlineResponse2009Cardtransactions.limitPaymentDay) &&
        Objects.equals(this.limitPaymentAll, inlineResponse2009Cardtransactions.limitPaymentAll) &&
        Objects.equals(this.totalLimitAtmYear, inlineResponse2009Cardtransactions.totalLimitAtmYear) &&
        Objects.equals(this.totalLimitAtmMonth, inlineResponse2009Cardtransactions.totalLimitAtmMonth) &&
        Objects.equals(this.totalLimitAtmWeek, inlineResponse2009Cardtransactions.totalLimitAtmWeek) &&
        Objects.equals(this.totalLimitAtmDay, inlineResponse2009Cardtransactions.totalLimitAtmDay) &&
        Objects.equals(this.totalLimitAtmAll, inlineResponse2009Cardtransactions.totalLimitAtmAll) &&
        Objects.equals(this.totalLimitPaymentYear, inlineResponse2009Cardtransactions.totalLimitPaymentYear) &&
        Objects.equals(this.totalLimitPaymentMonth, inlineResponse2009Cardtransactions.totalLimitPaymentMonth) &&
        Objects.equals(this.totalLimitPaymentWeek, inlineResponse2009Cardtransactions.totalLimitPaymentWeek) &&
        Objects.equals(this.totalLimitPaymentDay, inlineResponse2009Cardtransactions.totalLimitPaymentDay) &&
        Objects.equals(this.totalLimitPaymentAll, inlineResponse2009Cardtransactions.totalLimitPaymentAll) &&
        Objects.equals(this.totalRows, inlineResponse2009Cardtransactions.totalRows);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cardtransactionId, cardId, walletId, acquirerId, walletCurrency, merchantId, merchantName, merchantCity, merchantCountry, mccCode, paymentLocalTime, publicToken, paymentAmount, paymentCurrency, fees, paymentCountry, paymentId, paymentStatus, paymentLocalAmount, posCardholderPresence, posPostcode, posCountry, posTerminalId, posCardPresence, panEntryMethod, authorizationNote, authorizationResponseCode, authorizationIssuerId, authorizationIssuerTime, authorizationMti, authorizedBalance, limitAtmYear, limitAtmMonth, limitAtmWeek, limitAtmDay, limitAtmAll, limitPaymentYear, limitPaymentMonth, limitPaymentWeek, limitPaymentDay, limitPaymentAll, totalLimitAtmYear, totalLimitAtmMonth, totalLimitAtmWeek, totalLimitAtmDay, totalLimitAtmAll, totalLimitPaymentYear, totalLimitPaymentMonth, totalLimitPaymentWeek, totalLimitPaymentDay, totalLimitPaymentAll, totalRows);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TreezorInlineResponse2009Cardtransactions {\n");
    
    sb.append("    cardtransactionId: ").append(toIndentedString(cardtransactionId)).append("\n");
    sb.append("    cardId: ").append(toIndentedString(cardId)).append("\n");
    sb.append("    walletId: ").append(toIndentedString(walletId)).append("\n");
    sb.append("    acquirerId: ").append(toIndentedString(acquirerId)).append("\n");
    sb.append("    walletCurrency: ").append(toIndentedString(walletCurrency)).append("\n");
    sb.append("    merchantId: ").append(toIndentedString(merchantId)).append("\n");
    sb.append("    merchantName: ").append(toIndentedString(merchantName)).append("\n");
    sb.append("    merchantCity: ").append(toIndentedString(merchantCity)).append("\n");
    sb.append("    merchantCountry: ").append(toIndentedString(merchantCountry)).append("\n");
    sb.append("    mccCode: ").append(toIndentedString(mccCode)).append("\n");
    sb.append("    paymentLocalTime: ").append(toIndentedString(paymentLocalTime)).append("\n");
    sb.append("    publicToken: ").append(toIndentedString(publicToken)).append("\n");
    sb.append("    paymentAmount: ").append(toIndentedString(paymentAmount)).append("\n");
    sb.append("    paymentCurrency: ").append(toIndentedString(paymentCurrency)).append("\n");
    sb.append("    fees: ").append(toIndentedString(fees)).append("\n");
    sb.append("    paymentCountry: ").append(toIndentedString(paymentCountry)).append("\n");
    sb.append("    paymentId: ").append(toIndentedString(paymentId)).append("\n");
    sb.append("    paymentStatus: ").append(toIndentedString(paymentStatus)).append("\n");
    sb.append("    paymentLocalAmount: ").append(toIndentedString(paymentLocalAmount)).append("\n");
    sb.append("    posCardholderPresence: ").append(toIndentedString(posCardholderPresence)).append("\n");
    sb.append("    posPostcode: ").append(toIndentedString(posPostcode)).append("\n");
    sb.append("    posCountry: ").append(toIndentedString(posCountry)).append("\n");
    sb.append("    posTerminalId: ").append(toIndentedString(posTerminalId)).append("\n");
    sb.append("    posCardPresence: ").append(toIndentedString(posCardPresence)).append("\n");
    sb.append("    panEntryMethod: ").append(toIndentedString(panEntryMethod)).append("\n");
    sb.append("    authorizationNote: ").append(toIndentedString(authorizationNote)).append("\n");
    sb.append("    authorizationResponseCode: ").append(toIndentedString(authorizationResponseCode)).append("\n");
    sb.append("    authorizationIssuerId: ").append(toIndentedString(authorizationIssuerId)).append("\n");
    sb.append("    authorizationIssuerTime: ").append(toIndentedString(authorizationIssuerTime)).append("\n");
    sb.append("    authorizationMti: ").append(toIndentedString(authorizationMti)).append("\n");
    sb.append("    authorizedBalance: ").append(toIndentedString(authorizedBalance)).append("\n");
    sb.append("    limitAtmYear: ").append(toIndentedString(limitAtmYear)).append("\n");
    sb.append("    limitAtmMonth: ").append(toIndentedString(limitAtmMonth)).append("\n");
    sb.append("    limitAtmWeek: ").append(toIndentedString(limitAtmWeek)).append("\n");
    sb.append("    limitAtmDay: ").append(toIndentedString(limitAtmDay)).append("\n");
    sb.append("    limitAtmAll: ").append(toIndentedString(limitAtmAll)).append("\n");
    sb.append("    limitPaymentYear: ").append(toIndentedString(limitPaymentYear)).append("\n");
    sb.append("    limitPaymentMonth: ").append(toIndentedString(limitPaymentMonth)).append("\n");
    sb.append("    limitPaymentWeek: ").append(toIndentedString(limitPaymentWeek)).append("\n");
    sb.append("    limitPaymentDay: ").append(toIndentedString(limitPaymentDay)).append("\n");
    sb.append("    limitPaymentAll: ").append(toIndentedString(limitPaymentAll)).append("\n");
    sb.append("    totalLimitAtmYear: ").append(toIndentedString(totalLimitAtmYear)).append("\n");
    sb.append("    totalLimitAtmMonth: ").append(toIndentedString(totalLimitAtmMonth)).append("\n");
    sb.append("    totalLimitAtmWeek: ").append(toIndentedString(totalLimitAtmWeek)).append("\n");
    sb.append("    totalLimitAtmDay: ").append(toIndentedString(totalLimitAtmDay)).append("\n");
    sb.append("    totalLimitAtmAll: ").append(toIndentedString(totalLimitAtmAll)).append("\n");
    sb.append("    totalLimitPaymentYear: ").append(toIndentedString(totalLimitPaymentYear)).append("\n");
    sb.append("    totalLimitPaymentMonth: ").append(toIndentedString(totalLimitPaymentMonth)).append("\n");
    sb.append("    totalLimitPaymentWeek: ").append(toIndentedString(totalLimitPaymentWeek)).append("\n");
    sb.append("    totalLimitPaymentDay: ").append(toIndentedString(totalLimitPaymentDay)).append("\n");
    sb.append("    totalLimitPaymentAll: ").append(toIndentedString(totalLimitPaymentAll)).append("\n");
    sb.append("    totalRows: ").append(toIndentedString(totalRows)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

