/*
 * Treezor
 * Treezor API.  more info [here](https://www.treezor.com). 
 *
 * OpenAPI spec version: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * TreezorBusinesssearchsBusinessinformations
 */

public class TreezorBusinesssearchsBusinessinformations {
  @JsonProperty("legalName")
  private String legalName = null;

  @JsonProperty("phone")
  private String phone = null;

  @JsonProperty("legalTvaNumber")
  private String legalTvaNumber = null;

  @JsonProperty("legalRegistrationNumber")
  private String legalRegistrationNumber = null;

  /**
   * | Code | Description | | ---- | ----------- | |  D   | Deleted     | |  N   | Company non diffusible (Insee) | |  I   | Inactive (Insee) | |  A   | Economically active | |  C   | Closed | |  T   | Transfered | |  S   | Economically stopped (Insee) | |  L   | Liquidation | |  O   | Dormant company | 
   */
  public enum StatusEnum {
    D("D"),
    
    N("N"),
    
    I("I"),
    
    A("A"),
    
    C("C"),
    
    T("T"),
    
    S("S"),
    
    L("L"),
    
    O("O");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("status")
  private StatusEnum status = null;

  @JsonProperty("officeType")
  private Integer officeType = null;

  @JsonProperty("safeNumber")
  private String safeNumber = null;

  @JsonProperty("activityType")
  private String activityType = null;

  @JsonProperty("externalId")
  private String externalId = null;

  @JsonProperty("address1")
  private String address1 = null;

  @JsonProperty("postcode")
  private String postcode = null;

  @JsonProperty("city")
  private String city = null;

  @JsonProperty("state")
  private String state = null;

  @JsonProperty("country")
  private String country = null;

  @JsonProperty("tradename")
  private String tradename = null;

  public TreezorBusinesssearchsBusinessinformations legalName(String legalName) {
    this.legalName = legalName;
    return this;
  }

   /**
   * Business commercial name.
   * @return legalName
  **/
  @ApiModelProperty(value = "Business commercial name.")
  public String getLegalName() {
    return legalName;
  }

  public void setLegalName(String legalName) {
    this.legalName = legalName;
  }

  public TreezorBusinesssearchsBusinessinformations phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Business phone number.
   * @return phone
  **/
  @ApiModelProperty(value = "Business phone number.")
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public TreezorBusinesssearchsBusinessinformations legalTvaNumber(String legalTvaNumber) {
    this.legalTvaNumber = legalTvaNumber;
    return this;
  }

   /**
   * Business VAT number.
   * @return legalTvaNumber
  **/
  @ApiModelProperty(value = "Business VAT number.")
  public String getLegalTvaNumber() {
    return legalTvaNumber;
  }

  public void setLegalTvaNumber(String legalTvaNumber) {
    this.legalTvaNumber = legalTvaNumber;
  }

  public TreezorBusinesssearchsBusinessinformations legalRegistrationNumber(String legalRegistrationNumber) {
    this.legalRegistrationNumber = legalRegistrationNumber;
    return this;
  }

   /**
   * Business registration number.
   * @return legalRegistrationNumber
  **/
  @ApiModelProperty(value = "Business registration number.")
  public String getLegalRegistrationNumber() {
    return legalRegistrationNumber;
  }

  public void setLegalRegistrationNumber(String legalRegistrationNumber) {
    this.legalRegistrationNumber = legalRegistrationNumber;
  }

  public TreezorBusinesssearchsBusinessinformations status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * | Code | Description | | ---- | ----------- | |  D   | Deleted     | |  N   | Company non diffusible (Insee) | |  I   | Inactive (Insee) | |  A   | Economically active | |  C   | Closed | |  T   | Transfered | |  S   | Economically stopped (Insee) | |  L   | Liquidation | |  O   | Dormant company | 
   * @return status
  **/
  @ApiModelProperty(value = "| Code | Description | | ---- | ----------- | |  D   | Deleted     | |  N   | Company non diffusible (Insee) | |  I   | Inactive (Insee) | |  A   | Economically active | |  C   | Closed | |  T   | Transfered | |  S   | Economically stopped (Insee) | |  L   | Liquidation | |  O   | Dormant company | ")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public TreezorBusinesssearchsBusinessinformations officeType(Integer officeType) {
    this.officeType = officeType;
    return this;
  }

   /**
   * | Code | Description | | ---- | ----        | |  0   | Secondary establishment | |  1   | Headquarter | 
   * @return officeType
  **/
  @ApiModelProperty(value = "| Code | Description | | ---- | ----        | |  0   | Secondary establishment | |  1   | Headquarter | ")
  public Integer getOfficeType() {
    return officeType;
  }

  public void setOfficeType(Integer officeType) {
    this.officeType = officeType;
  }

  public TreezorBusinesssearchsBusinessinformations safeNumber(String safeNumber) {
    this.safeNumber = safeNumber;
    return this;
  }

   /**
   * Business SAFE number.
   * @return safeNumber
  **/
  @ApiModelProperty(value = "Business SAFE number.")
  public String getSafeNumber() {
    return safeNumber;
  }

  public void setSafeNumber(String safeNumber) {
    this.safeNumber = safeNumber;
  }

  public TreezorBusinesssearchsBusinessinformations activityType(String activityType) {
    this.activityType = activityType;
    return this;
  }

   /**
   * Business sector. Code NAF in France.
   * @return activityType
  **/
  @ApiModelProperty(value = "Business sector. Code NAF in France.")
  public String getActivityType() {
    return activityType;
  }

  public void setActivityType(String activityType) {
    this.activityType = activityType;
  }

  public TreezorBusinesssearchsBusinessinformations externalId(String externalId) {
    this.externalId = externalId;
    return this;
  }

   /**
   * Business external id.
   * @return externalId
  **/
  @ApiModelProperty(value = "Business external id.")
  public String getExternalId() {
    return externalId;
  }

  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }

  public TreezorBusinesssearchsBusinessinformations address1(String address1) {
    this.address1 = address1;
    return this;
  }

   /**
   * Business&#39; street.
   * @return address1
  **/
  @ApiModelProperty(value = "Business' street.")
  public String getAddress1() {
    return address1;
  }

  public void setAddress1(String address1) {
    this.address1 = address1;
  }

  public TreezorBusinesssearchsBusinessinformations postcode(String postcode) {
    this.postcode = postcode;
    return this;
  }

   /**
   * Business&#39; postal code.
   * @return postcode
  **/
  @ApiModelProperty(value = "Business' postal code.")
  public String getPostcode() {
    return postcode;
  }

  public void setPostcode(String postcode) {
    this.postcode = postcode;
  }

  public TreezorBusinesssearchsBusinessinformations city(String city) {
    this.city = city;
    return this;
  }

   /**
   * Business&#39; city.
   * @return city
  **/
  @ApiModelProperty(value = "Business' city.")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public TreezorBusinesssearchsBusinessinformations state(String state) {
    this.state = state;
    return this;
  }

   /**
   * Business&#39; province.
   * @return state
  **/
  @ApiModelProperty(value = "Business' province.")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public TreezorBusinesssearchsBusinessinformations country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Business&#39; country.
   * @return country
  **/
  @ApiModelProperty(value = "Business' country.")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public TreezorBusinesssearchsBusinessinformations tradename(String tradename) {
    this.tradename = tradename;
    return this;
  }

   /**
   * Business trade name
   * @return tradename
  **/
  @ApiModelProperty(value = "Business trade name")
  public String getTradename() {
    return tradename;
  }

  public void setTradename(String tradename) {
    this.tradename = tradename;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TreezorBusinesssearchsBusinessinformations businesssearchsBusinessinformations = (TreezorBusinesssearchsBusinessinformations) o;
    return Objects.equals(this.legalName, businesssearchsBusinessinformations.legalName) &&
        Objects.equals(this.phone, businesssearchsBusinessinformations.phone) &&
        Objects.equals(this.legalTvaNumber, businesssearchsBusinessinformations.legalTvaNumber) &&
        Objects.equals(this.legalRegistrationNumber, businesssearchsBusinessinformations.legalRegistrationNumber) &&
        Objects.equals(this.status, businesssearchsBusinessinformations.status) &&
        Objects.equals(this.officeType, businesssearchsBusinessinformations.officeType) &&
        Objects.equals(this.safeNumber, businesssearchsBusinessinformations.safeNumber) &&
        Objects.equals(this.activityType, businesssearchsBusinessinformations.activityType) &&
        Objects.equals(this.externalId, businesssearchsBusinessinformations.externalId) &&
        Objects.equals(this.address1, businesssearchsBusinessinformations.address1) &&
        Objects.equals(this.postcode, businesssearchsBusinessinformations.postcode) &&
        Objects.equals(this.city, businesssearchsBusinessinformations.city) &&
        Objects.equals(this.state, businesssearchsBusinessinformations.state) &&
        Objects.equals(this.country, businesssearchsBusinessinformations.country) &&
        Objects.equals(this.tradename, businesssearchsBusinessinformations.tradename);
  }

  @Override
  public int hashCode() {
    return Objects.hash(legalName, phone, legalTvaNumber, legalRegistrationNumber, status, officeType, safeNumber, activityType, externalId, address1, postcode, city, state, country, tradename);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TreezorBusinesssearchsBusinessinformations {\n");
    
    sb.append("    legalName: ").append(toIndentedString(legalName)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    legalTvaNumber: ").append(toIndentedString(legalTvaNumber)).append("\n");
    sb.append("    legalRegistrationNumber: ").append(toIndentedString(legalRegistrationNumber)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    officeType: ").append(toIndentedString(officeType)).append("\n");
    sb.append("    safeNumber: ").append(toIndentedString(safeNumber)).append("\n");
    sb.append("    activityType: ").append(toIndentedString(activityType)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    address1: ").append(toIndentedString(address1)).append("\n");
    sb.append("    postcode: ").append(toIndentedString(postcode)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    tradename: ").append(toIndentedString(tradename)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

