/*
 * Treezor
 * Treezor API.  more info [here](https://www.treezor.com). 
 *
 * OpenAPI spec version: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.TreezorVirtualiban;
import java.util.ArrayList;
import java.util.List;

/**
 * TreezorInlineResponse20027
 */

public class TreezorInlineResponse20027 {
  @JsonProperty("virtualibans")
  private List<TreezorVirtualiban> virtualibans = null;

  public TreezorInlineResponse20027 virtualibans(List<TreezorVirtualiban> virtualibans) {
    this.virtualibans = virtualibans;
    return this;
  }

  public TreezorInlineResponse20027 addVirtualibansItem(TreezorVirtualiban virtualibansItem) {
    if (this.virtualibans == null) {
      this.virtualibans = new ArrayList<>();
    }
    this.virtualibans.add(virtualibansItem);
    return this;
  }

   /**
   * Get virtualibans
   * @return virtualibans
  **/
  @ApiModelProperty(value = "")
  public List<TreezorVirtualiban> getVirtualibans() {
    return virtualibans;
  }

  public void setVirtualibans(List<TreezorVirtualiban> virtualibans) {
    this.virtualibans = virtualibans;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TreezorInlineResponse20027 inlineResponse20027 = (TreezorInlineResponse20027) o;
    return Objects.equals(this.virtualibans, inlineResponse20027.virtualibans);
  }

  @Override
  public int hashCode() {
    return Objects.hash(virtualibans);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TreezorInlineResponse20027 {\n");
    
    sb.append("    virtualibans: ").append(toIndentedString(virtualibans)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

