/*
 * Treezor
 * Treezor API.  more info [here](https://www.treezor.com). 
 *
 * OpenAPI spec version: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.TreezorBody;
import io.swagger.client.model.TreezorBody1;
import io.swagger.client.model.TreezorInlineResponse2002;
import io.swagger.client.model.TreezorInlineResponseDefault;

import io.swagger.client.Configuration;

import org.junit.Test;
import org.junit.Ignore;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.runner.RunWith;

import io.vertx.core.AsyncResult;
import io.vertx.core.Handler;
import io.vertx.core.json.JsonObject;
import io.vertx.core.Vertx;
import io.vertx.ext.unit.junit.VertxUnitRunner;
import io.vertx.ext.unit.junit.RunTestOnContext;
import io.vertx.ext.unit.TestContext;
import io.vertx.ext.unit.Async;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BeneficiariesApi
 */
@RunWith(VertxUnitRunner.class)
@Ignore
public class BeneficiariesApiTest {

    private BeneficiariesApi api;

    @Rule
    public RunTestOnContext rule = new RunTestOnContext();

    @BeforeClass
    public void setupApiClient() {
        JsonObject config = new JsonObject();
        Vertx vertx = rule.vertx();
        Configuration.setupDefaultApiClient(vertx, config);

        api = new BeneficiariesApiImpl();
    }
    
    /**
     * search beneficiary bank accounts
     * Get beneficiary bank accounts that match search criteria.
     *
     * @param context Vertx test context for doing assertions
     */
    @Test
    public void getBeneficiariesTest(TestContext context) {
        Async async = context.async();
        String accessSignature = null;
        String accessTag = null;
        Integer accessUserId = null;
        String accessUserIp = null;
        List<String> fields = null;
        String filter = null;
        Integer id = null;
        Integer userId = null;
        String iban = null;
        String bic = null;
        String nickName = null;
        String name = null;
        Integer pageNumber = null;
        Integer pageCount = null;
        String sortBy = null;
        String sortOrder = null;
        api.getBeneficiaries(accessSignature, accessTag, accessUserId, accessUserIp, fields, filter, id, userId, iban, bic, nickName, name, pageNumber, pageCount, sortBy, sortOrder, result -> {
            // TODO: test validations
            async.complete();
        });
    }
    
    /**
     * get a beneficiary bank account
     * Get a beneficiary bank account from the system.
     *
     * @param context Vertx test context for doing assertions
     */
    @Test
    public void getBeneficiaryTest(TestContext context) {
        Async async = context.async();
        Long id = null;
        List<String> fields = null;
        api.getBeneficiary(id, fields, result -> {
            // TODO: test validations
            async.complete();
        });
    }
    
    /**
     * create a beneficiary
     * Create a new benefeciary bank account in the system.
     *
     * @param context Vertx test context for doing assertions
     */
    @Test
    public void postBeneficiaryTest(TestContext context) {
        Async async = context.async();
        String accessSignature = null;
        String accessTag = null;
        Integer accessUserId = null;
        String accessUserIp = null;
        TreezorBody body = null;
        api.postBeneficiary(accessSignature, accessTag, accessUserId, accessUserIp, body, result -> {
            // TODO: test validations
            async.complete();
        });
    }
    
    /**
     * edit a beneficiary
     * Edit a benefeciary bank account in the system.
     *
     * @param context Vertx test context for doing assertions
     */
    @Test
    public void putBeneficiaryTest(TestContext context) {
        Async async = context.async();
        Integer id = null;
        String accessSignature = null;
        String accessTag = null;
        Integer accessUserId = null;
        String accessUserIp = null;
        TreezorBody1 body = null;
        api.putBeneficiary(id, accessSignature, accessTag, accessUserId, accessUserIp, body, result -> {
            // TODO: test validations
            async.complete();
        });
    }
    
}