/*
 * Treezor
 * Treezor API.  more info [here](https://www.treezor.com). 
 *
 * OpenAPI spec version: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.TreezorInlineResponse2007;
import io.swagger.client.model.TreezorInlineResponseDefault;

import io.swagger.client.Configuration;

import org.junit.Test;
import org.junit.Ignore;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.runner.RunWith;

import io.vertx.core.AsyncResult;
import io.vertx.core.Handler;
import io.vertx.core.json.JsonObject;
import io.vertx.core.Vertx;
import io.vertx.ext.unit.junit.VertxUnitRunner;
import io.vertx.ext.unit.junit.RunTestOnContext;
import io.vertx.ext.unit.TestContext;
import io.vertx.ext.unit.Async;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CardDigitalizationsApi
 */
@RunWith(VertxUnitRunner.class)
@Ignore
public class CardDigitalizationsApiTest {

    private CardDigitalizationsApi api;

    @Rule
    public RunTestOnContext rule = new RunTestOnContext();

    @BeforeClass
    public void setupApiClient() {
        JsonObject config = new JsonObject();
        Vertx vertx = rule.vertx();
        Configuration.setupDefaultApiClient(vertx, config);

        api = new CardDigitalizationsApiImpl();
    }
    
    /**
     * Get a card digitalizations based on its internal id
     * Get a card digitalizations based on its internal id
     *
     * @param context Vertx test context for doing assertions
     */
    @Test
    public void cardDigitalizationsIdTest(TestContext context) {
        Async async = context.async();
        Long id = null;
        String fields = null;
        api.cardDigitalizationsId(id, fields, result -> {
            // TODO: test validations
            async.complete();
        });
    }
    
    /**
     * Deletes a payment Token
     * Deletes a payment Token
     *
     * @param context Vertx test context for doing assertions
     */
    @Test
    public void deletecardDigitalizationsIdTest(TestContext context) {
        Async async = context.async();
        Long id = null;
        String reasonCode = null;
        api.deletecardDigitalizationsId(id, reasonCode, result -> {
            // TODO: test validations
            async.complete();
        });
    }
    
    /**
     * Update the status of a payment Token
     * Update the status of a payment Token
     *
     * @param context Vertx test context for doing assertions
     */
    @Test
    public void putcardDigitalizationsIdTest(TestContext context) {
        Async async = context.async();
        Long id = null;
        String status = null;
        String reasonCode = null;
        api.putcardDigitalizationsId(id, status, reasonCode, result -> {
            // TODO: test validations
            async.complete();
        });
    }
    
    /**
     * search for card digitalizations
     * Search for card digitalizations.
     *
     * @param context Vertx test context for doing assertions
     */
    @Test
    public void readcardDigitalizationsTest(TestContext context) {
        Async async = context.async();
        String accessSignature = null;
        String accessTag = null;
        Integer accessUserId = null;
        String accessUserIp = null;
        String filter = null;
        String fields = null;
        api.readcardDigitalizations(accessSignature, accessTag, accessUserId, accessUserIp, filter, fields, result -> {
            // TODO: test validations
            async.complete();
        });
    }
    
}