/*
 * Treezor
 * Treezor API.  more info [here](https://www.treezor.com). 
 *
 * OpenAPI spec version: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.TreezorBody7;
import io.swagger.client.model.TreezorBody8;
import io.swagger.client.model.TreezorInlineResponse20015;
import io.swagger.client.model.TreezorInlineResponseDefault;

import io.swagger.client.Configuration;

import org.junit.Test;
import org.junit.Ignore;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.runner.RunWith;

import io.vertx.core.AsyncResult;
import io.vertx.core.Handler;
import io.vertx.core.json.JsonObject;
import io.vertx.core.Vertx;
import io.vertx.ext.unit.junit.VertxUnitRunner;
import io.vertx.ext.unit.junit.RunTestOnContext;
import io.vertx.ext.unit.TestContext;
import io.vertx.ext.unit.Async;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MccRestrictionGroupsApi
 */
@RunWith(VertxUnitRunner.class)
@Ignore
public class MccRestrictionGroupsApiTest {

    private MccRestrictionGroupsApi api;

    @Rule
    public RunTestOnContext rule = new RunTestOnContext();

    @BeforeClass
    public void setupApiClient() {
        JsonObject config = new JsonObject();
        Vertx vertx = rule.vertx();
        Configuration.setupDefaultApiClient(vertx, config);

        api = new MccRestrictionGroupsApiImpl();
    }
    
    /**
     * cancel a mcc group
     * Cancel a mcc restriction group from the system.
     *
     * @param context Vertx test context for doing assertions
     */
    @Test
    public void deleteMccRestrictionGroupsTest(TestContext context) {
        Async async = context.async();
        Long id = null;
        List<String> fields = null;
        api.deleteMccRestrictionGroups(id, fields, result -> {
            // TODO: test validations
            async.complete();
        });
    }
    
    /**
     * search mcc restriction groups
     * Get mcc restriction groups that match search criteria.
     *
     * @param context Vertx test context for doing assertions
     */
    @Test
    public void getMccRestrictionGroupsTest(TestContext context) {
        Async async = context.async();
        String accessSignature = null;
        String accessTag = null;
        Integer accessUserId = null;
        String accessUserIp = null;
        List<String> fields = null;
        String filter = null;
        Integer pageNumber = null;
        Integer pageCount = null;
        String sortBy = null;
        String sortOrder = null;
        api.getMccRestrictionGroups(accessSignature, accessTag, accessUserId, accessUserIp, fields, filter, pageNumber, pageCount, sortBy, sortOrder, result -> {
            // TODO: test validations
            async.complete();
        });
    }
    
    /**
     * get a mcc group
     * Get a mcc group from the system.
     *
     * @param context Vertx test context for doing assertions
     */
    @Test
    public void getMccRestrictionGroupsIdTest(TestContext context) {
        Async async = context.async();
        Long id = null;
        List<String> fields = null;
        api.getMccRestrictionGroupsId(id, fields, result -> {
            // TODO: test validations
            async.complete();
        });
    }
    
    /**
     * create a mccRestrictionGroup
     * Create a new mcc restriction group in the system.
     *
     * @param context Vertx test context for doing assertions
     */
    @Test
    public void postMccRestrictionGroupTest(TestContext context) {
        Async async = context.async();
        String accessSignature = null;
        String accessTag = null;
        Integer accessUserId = null;
        String accessUserIp = null;
        List<String> fields = null;
        TreezorBody7 body = null;
        api.postMccRestrictionGroup(accessSignature, accessTag, accessUserId, accessUserIp, fields, body, result -> {
            // TODO: test validations
            async.complete();
        });
    }
    
    /**
     * edit a mcc restriction group
     * Edit a mcc restriction group in the system.
     *
     * @param context Vertx test context for doing assertions
     */
    @Test
    public void putMccRestrictionGroupsTest(TestContext context) {
        Async async = context.async();
        Integer id = null;
        String accessSignature = null;
        String accessTag = null;
        Integer accessUserId = null;
        String accessUserIp = null;
        TreezorBody8 body = null;
        api.putMccRestrictionGroups(id, accessSignature, accessTag, accessUserId, accessUserIp, body, result -> {
            // TODO: test validations
            async.complete();
        });
    }
    
}