FROM maven:3.6.3-jdk-13

# This is needed so vertx can stop the current process using `ps` and redeploy
RUN set -eux; \
    yum install -y procps

ENV LUXLUNCH_HOME /luxlunch-server
ENV MAVEN_CACHE_HOME /m2repo

# Options for the JVM
ENV MAVEN_OPTS=-Dmaven.repo.local=$MAVEN_CACHE_HOME \
                -Dlog4j.configuration=log4j2.xml \
                -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.SLF4JLogDelegateFactory

# Maven params
ENV CONFIG=src/config/docker.json
ENV MAVEN_ARGS="-Dvertx.config=$CONFIG"

# Java debug params
ENV DEBUG_SUSPEND=false
ENV DEBUG_PORT=5005
ENV CONFIG=src/config/docker.json
ENV MAVEN_ARGS="-Dvertx.config=$CONFIG -Ddebug.suspend=$DEBUG_SUSPEND -Ddebug.port=0.0.0.0:$DEBUG_PORT -Dvertx.development=true"

VOLUME $LUXLUNCH_HOME
VOLUME $MAVEN_CACHE_HOME

EXPOSE 8080

WORKDIR $LUXLUNCH_HOME/luxlunch-account-microservice
ENTRYPOINT ["sh", "-c"]
CMD ["mvn clean compile vertx:debug $MAVEN_ARGS"]
