/*
 * Treezor
 * Treezor API.  more info [here](https://www.treezor.com). 
 *
 * OpenAPI spec version: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.treezor.sandbox.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.treezor.sandbox.model.InlineResponse20010Cardtransactions;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse20010
 */

public class InlineResponse20010 {
  @SerializedName("cardtransactions")
  private List<InlineResponse20010Cardtransactions> cardtransactions = null;

  public InlineResponse20010 cardtransactions(List<InlineResponse20010Cardtransactions> cardtransactions) {
    this.cardtransactions = cardtransactions;
    return this;
  }

  public InlineResponse20010 addCardtransactionsItem(InlineResponse20010Cardtransactions cardtransactionsItem) {
    if (this.cardtransactions == null) {
      this.cardtransactions = new ArrayList<InlineResponse20010Cardtransactions>();
    }
    this.cardtransactions.add(cardtransactionsItem);
    return this;
  }

   /**
   * Get cardtransactions
   * @return cardtransactions
  **/
  @ApiModelProperty(value = "")
  public List<InlineResponse20010Cardtransactions> getCardtransactions() {
    return cardtransactions;
  }

  public void setCardtransactions(List<InlineResponse20010Cardtransactions> cardtransactions) {
    this.cardtransactions = cardtransactions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20010 inlineResponse20010 = (InlineResponse20010) o;
    return Objects.equals(this.cardtransactions, inlineResponse20010.cardtransactions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cardtransactions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20010 {\n");
    
    sb.append("    cardtransactions: ").append(toIndentedString(cardtransactions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

