/*
 * Treezor
 * Treezor API.  more info [here](https://www.treezor.com). 
 *
 * OpenAPI spec version: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.treezor.sandbox.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Payin
 */

public class Payin {
  @SerializedName("payinId")
  private Integer payinId = null;

  @SerializedName("payinTag")
  private String payinTag = null;

  /**
   * Gets or Sets payinStatus
   */
  @JsonAdapter(PayinStatusEnum.Adapter.class)
  public enum PayinStatusEnum {
    PENDING("PENDING"),
    
    CANCELED("CANCELED"),
    
    VALIDATED("VALIDATED");

    private String value;

    PayinStatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static PayinStatusEnum fromValue(String text) {
      for (PayinStatusEnum b : PayinStatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<PayinStatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PayinStatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public PayinStatusEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return PayinStatusEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("payinStatus")
  private PayinStatusEnum payinStatus = null;

  @SerializedName("codeStatus")
  private Integer codeStatus = null;

  @SerializedName("informationStatus")
  private String informationStatus = null;

  @SerializedName("walletId")
  private Integer walletId = null;

  @SerializedName("userId")
  private Integer userId = null;

  @SerializedName("cartId")
  private Integer cartId = null;

  @SerializedName("walletEventName")
  private String walletEventName = null;

  @SerializedName("walletAlias")
  private String walletAlias = null;

  @SerializedName("userFirstname")
  private String userFirstname = null;

  @SerializedName("userLastname")
  private String userLastname = null;

  @SerializedName("messageToUser")
  private String messageToUser = null;

  @SerializedName("paymentMethodId")
  private Integer paymentMethodId = null;

  @SerializedName("subtotalItems")
  private String subtotalItems = null;

  @SerializedName("subtotalServices")
  private String subtotalServices = null;

  @SerializedName("subtotalTax")
  private String subtotalTax = null;

  @SerializedName("amount")
  private String amount = null;

  @SerializedName("currency")
  private String currency = null;

  @SerializedName("distributorFee")
  private String distributorFee = null;

  @SerializedName("createdDate")
  private String createdDate = null;

  @SerializedName("createdIp")
  private String createdIp = null;

  @SerializedName("paymentHtml")
  private String paymentHtml = null;

  @SerializedName("paymentLanguage")
  private String paymentLanguage = null;

  @SerializedName("paymentPostUrl")
  private String paymentPostUrl = null;

  @SerializedName("paymentPostDataUrl")
  private String paymentPostDataUrl = null;

  @SerializedName("paymentAcceptedUrl")
  private String paymentAcceptedUrl = null;

  @SerializedName("paymentWaitingUrl")
  private String paymentWaitingUrl = null;

  @SerializedName("paymentRefusedUrl")
  private String paymentRefusedUrl = null;

  @SerializedName("paymentCanceledUrl")
  private String paymentCanceledUrl = null;

  @SerializedName("paymentExceptionUrl")
  private String paymentExceptionUrl = null;

  @SerializedName("ibanFullname")
  private String ibanFullname = null;

  @SerializedName("ibanId")
  private String ibanId = null;

  @SerializedName("ibanBic")
  private String ibanBic = null;

  @SerializedName("ibanTxEndToEndId")
  private String ibanTxEndToEndId = null;

  @SerializedName("ibanTxId")
  private String ibanTxId = null;

  @SerializedName("refundAmount")
  private String refundAmount = null;

  @SerializedName("totalRows")
  private Integer totalRows = null;

  @SerializedName("forwardUrl")
  private String forwardUrl = null;

  @SerializedName("payinDate")
  private String payinDate = null;

  @SerializedName("mandateId")
  private Integer mandateId = null;

  @SerializedName("creditorName")
  private String creditorName = null;

  @SerializedName("creditorAddressLine")
  private String creditorAddressLine = null;

  @SerializedName("creditorCountry")
  private String creditorCountry = null;

  @SerializedName("creditorIban")
  private String creditorIban = null;

  @SerializedName("creditorBIC")
  private String creditorBIC = null;

  @SerializedName("virtualIbanId")
  private Integer virtualIbanId = null;

  @SerializedName("virtualIbanReference")
  private String virtualIbanReference = null;

  public Payin payinId(Integer payinId) {
    this.payinId = payinId;
    return this;
  }

   /**
   * Get payinId
   * @return payinId
  **/
  @ApiModelProperty(value = "")
  public Integer getPayinId() {
    return payinId;
  }

  public void setPayinId(Integer payinId) {
    this.payinId = payinId;
  }

  public Payin payinTag(String payinTag) {
    this.payinTag = payinTag;
    return this;
  }

   /**
   * Get payinTag
   * @return payinTag
  **/
  @ApiModelProperty(value = "")
  public String getPayinTag() {
    return payinTag;
  }

  public void setPayinTag(String payinTag) {
    this.payinTag = payinTag;
  }

  public Payin payinStatus(PayinStatusEnum payinStatus) {
    this.payinStatus = payinStatus;
    return this;
  }

   /**
   * Get payinStatus
   * @return payinStatus
  **/
  @ApiModelProperty(value = "")
  public PayinStatusEnum getPayinStatus() {
    return payinStatus;
  }

  public void setPayinStatus(PayinStatusEnum payinStatus) {
    this.payinStatus = payinStatus;
  }

  public Payin codeStatus(Integer codeStatus) {
    this.codeStatus = codeStatus;
    return this;
  }

   /**
   * Get codeStatus
   * @return codeStatus
  **/
  @ApiModelProperty(value = "")
  public Integer getCodeStatus() {
    return codeStatus;
  }

  public void setCodeStatus(Integer codeStatus) {
    this.codeStatus = codeStatus;
  }

  public Payin informationStatus(String informationStatus) {
    this.informationStatus = informationStatus;
    return this;
  }

   /**
   * Get informationStatus
   * @return informationStatus
  **/
  @ApiModelProperty(value = "")
  public String getInformationStatus() {
    return informationStatus;
  }

  public void setInformationStatus(String informationStatus) {
    this.informationStatus = informationStatus;
  }

  public Payin walletId(Integer walletId) {
    this.walletId = walletId;
    return this;
  }

   /**
   * Get walletId
   * @return walletId
  **/
  @ApiModelProperty(value = "")
  public Integer getWalletId() {
    return walletId;
  }

  public void setWalletId(Integer walletId) {
    this.walletId = walletId;
  }

  public Payin userId(Integer userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(value = "")
  public Integer getUserId() {
    return userId;
  }

  public void setUserId(Integer userId) {
    this.userId = userId;
  }

  public Payin cartId(Integer cartId) {
    this.cartId = cartId;
    return this;
  }

   /**
   * Get cartId
   * @return cartId
  **/
  @ApiModelProperty(value = "")
  public Integer getCartId() {
    return cartId;
  }

  public void setCartId(Integer cartId) {
    this.cartId = cartId;
  }

  public Payin walletEventName(String walletEventName) {
    this.walletEventName = walletEventName;
    return this;
  }

   /**
   * Get walletEventName
   * @return walletEventName
  **/
  @ApiModelProperty(value = "")
  public String getWalletEventName() {
    return walletEventName;
  }

  public void setWalletEventName(String walletEventName) {
    this.walletEventName = walletEventName;
  }

  public Payin walletAlias(String walletAlias) {
    this.walletAlias = walletAlias;
    return this;
  }

   /**
   * Get walletAlias
   * @return walletAlias
  **/
  @ApiModelProperty(value = "")
  public String getWalletAlias() {
    return walletAlias;
  }

  public void setWalletAlias(String walletAlias) {
    this.walletAlias = walletAlias;
  }

  public Payin userFirstname(String userFirstname) {
    this.userFirstname = userFirstname;
    return this;
  }

   /**
   * Get userFirstname
   * @return userFirstname
  **/
  @ApiModelProperty(value = "")
  public String getUserFirstname() {
    return userFirstname;
  }

  public void setUserFirstname(String userFirstname) {
    this.userFirstname = userFirstname;
  }

  public Payin userLastname(String userLastname) {
    this.userLastname = userLastname;
    return this;
  }

   /**
   * Get userLastname
   * @return userLastname
  **/
  @ApiModelProperty(value = "")
  public String getUserLastname() {
    return userLastname;
  }

  public void setUserLastname(String userLastname) {
    this.userLastname = userLastname;
  }

  public Payin messageToUser(String messageToUser) {
    this.messageToUser = messageToUser;
    return this;
  }

   /**
   * Get messageToUser
   * @return messageToUser
  **/
  @ApiModelProperty(value = "")
  public String getMessageToUser() {
    return messageToUser;
  }

  public void setMessageToUser(String messageToUser) {
    this.messageToUser = messageToUser;
  }

  public Payin paymentMethodId(Integer paymentMethodId) {
    this.paymentMethodId = paymentMethodId;
    return this;
  }

   /**
   * Get paymentMethodId
   * @return paymentMethodId
  **/
  @ApiModelProperty(value = "")
  public Integer getPaymentMethodId() {
    return paymentMethodId;
  }

  public void setPaymentMethodId(Integer paymentMethodId) {
    this.paymentMethodId = paymentMethodId;
  }

  public Payin subtotalItems(String subtotalItems) {
    this.subtotalItems = subtotalItems;
    return this;
  }

   /**
   * Get subtotalItems
   * @return subtotalItems
  **/
  @ApiModelProperty(value = "")
  public String getSubtotalItems() {
    return subtotalItems;
  }

  public void setSubtotalItems(String subtotalItems) {
    this.subtotalItems = subtotalItems;
  }

  public Payin subtotalServices(String subtotalServices) {
    this.subtotalServices = subtotalServices;
    return this;
  }

   /**
   * Get subtotalServices
   * @return subtotalServices
  **/
  @ApiModelProperty(value = "")
  public String getSubtotalServices() {
    return subtotalServices;
  }

  public void setSubtotalServices(String subtotalServices) {
    this.subtotalServices = subtotalServices;
  }

  public Payin subtotalTax(String subtotalTax) {
    this.subtotalTax = subtotalTax;
    return this;
  }

   /**
   * Get subtotalTax
   * @return subtotalTax
  **/
  @ApiModelProperty(value = "")
  public String getSubtotalTax() {
    return subtotalTax;
  }

  public void setSubtotalTax(String subtotalTax) {
    this.subtotalTax = subtotalTax;
  }

  public Payin amount(String amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @ApiModelProperty(value = "")
  public String getAmount() {
    return amount;
  }

  public void setAmount(String amount) {
    this.amount = amount;
  }

  public Payin currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @ApiModelProperty(value = "")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public Payin distributorFee(String distributorFee) {
    this.distributorFee = distributorFee;
    return this;
  }

   /**
   * Get distributorFee
   * @return distributorFee
  **/
  @ApiModelProperty(value = "")
  public String getDistributorFee() {
    return distributorFee;
  }

  public void setDistributorFee(String distributorFee) {
    this.distributorFee = distributorFee;
  }

  public Payin createdDate(String createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Date YYYY-MM-DD HH:MM:SS
   * @return createdDate
  **/
  @ApiModelProperty(value = "Date YYYY-MM-DD HH:MM:SS")
  public String getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(String createdDate) {
    this.createdDate = createdDate;
  }

  public Payin createdIp(String createdIp) {
    this.createdIp = createdIp;
    return this;
  }

   /**
   * Get createdIp
   * @return createdIp
  **/
  @ApiModelProperty(value = "")
  public String getCreatedIp() {
    return createdIp;
  }

  public void setCreatedIp(String createdIp) {
    this.createdIp = createdIp;
  }

  public Payin paymentHtml(String paymentHtml) {
    this.paymentHtml = paymentHtml;
    return this;
  }

   /**
   * Get paymentHtml
   * @return paymentHtml
  **/
  @ApiModelProperty(value = "")
  public String getPaymentHtml() {
    return paymentHtml;
  }

  public void setPaymentHtml(String paymentHtml) {
    this.paymentHtml = paymentHtml;
  }

  public Payin paymentLanguage(String paymentLanguage) {
    this.paymentLanguage = paymentLanguage;
    return this;
  }

   /**
   * Get paymentLanguage
   * @return paymentLanguage
  **/
  @ApiModelProperty(value = "")
  public String getPaymentLanguage() {
    return paymentLanguage;
  }

  public void setPaymentLanguage(String paymentLanguage) {
    this.paymentLanguage = paymentLanguage;
  }

  public Payin paymentPostUrl(String paymentPostUrl) {
    this.paymentPostUrl = paymentPostUrl;
    return this;
  }

   /**
   * Get paymentPostUrl
   * @return paymentPostUrl
  **/
  @ApiModelProperty(value = "")
  public String getPaymentPostUrl() {
    return paymentPostUrl;
  }

  public void setPaymentPostUrl(String paymentPostUrl) {
    this.paymentPostUrl = paymentPostUrl;
  }

  public Payin paymentPostDataUrl(String paymentPostDataUrl) {
    this.paymentPostDataUrl = paymentPostDataUrl;
    return this;
  }

   /**
   * Get paymentPostDataUrl
   * @return paymentPostDataUrl
  **/
  @ApiModelProperty(value = "")
  public String getPaymentPostDataUrl() {
    return paymentPostDataUrl;
  }

  public void setPaymentPostDataUrl(String paymentPostDataUrl) {
    this.paymentPostDataUrl = paymentPostDataUrl;
  }

  public Payin paymentAcceptedUrl(String paymentAcceptedUrl) {
    this.paymentAcceptedUrl = paymentAcceptedUrl;
    return this;
  }

   /**
   * Get paymentAcceptedUrl
   * @return paymentAcceptedUrl
  **/
  @ApiModelProperty(value = "")
  public String getPaymentAcceptedUrl() {
    return paymentAcceptedUrl;
  }

  public void setPaymentAcceptedUrl(String paymentAcceptedUrl) {
    this.paymentAcceptedUrl = paymentAcceptedUrl;
  }

  public Payin paymentWaitingUrl(String paymentWaitingUrl) {
    this.paymentWaitingUrl = paymentWaitingUrl;
    return this;
  }

   /**
   * Get paymentWaitingUrl
   * @return paymentWaitingUrl
  **/
  @ApiModelProperty(value = "")
  public String getPaymentWaitingUrl() {
    return paymentWaitingUrl;
  }

  public void setPaymentWaitingUrl(String paymentWaitingUrl) {
    this.paymentWaitingUrl = paymentWaitingUrl;
  }

  public Payin paymentRefusedUrl(String paymentRefusedUrl) {
    this.paymentRefusedUrl = paymentRefusedUrl;
    return this;
  }

   /**
   * Get paymentRefusedUrl
   * @return paymentRefusedUrl
  **/
  @ApiModelProperty(value = "")
  public String getPaymentRefusedUrl() {
    return paymentRefusedUrl;
  }

  public void setPaymentRefusedUrl(String paymentRefusedUrl) {
    this.paymentRefusedUrl = paymentRefusedUrl;
  }

  public Payin paymentCanceledUrl(String paymentCanceledUrl) {
    this.paymentCanceledUrl = paymentCanceledUrl;
    return this;
  }

   /**
   * Get paymentCanceledUrl
   * @return paymentCanceledUrl
  **/
  @ApiModelProperty(value = "")
  public String getPaymentCanceledUrl() {
    return paymentCanceledUrl;
  }

  public void setPaymentCanceledUrl(String paymentCanceledUrl) {
    this.paymentCanceledUrl = paymentCanceledUrl;
  }

  public Payin paymentExceptionUrl(String paymentExceptionUrl) {
    this.paymentExceptionUrl = paymentExceptionUrl;
    return this;
  }

   /**
   * Get paymentExceptionUrl
   * @return paymentExceptionUrl
  **/
  @ApiModelProperty(value = "")
  public String getPaymentExceptionUrl() {
    return paymentExceptionUrl;
  }

  public void setPaymentExceptionUrl(String paymentExceptionUrl) {
    this.paymentExceptionUrl = paymentExceptionUrl;
  }

  public Payin ibanFullname(String ibanFullname) {
    this.ibanFullname = ibanFullname;
    return this;
  }

   /**
   * Get ibanFullname
   * @return ibanFullname
  **/
  @ApiModelProperty(value = "")
  public String getIbanFullname() {
    return ibanFullname;
  }

  public void setIbanFullname(String ibanFullname) {
    this.ibanFullname = ibanFullname;
  }

  public Payin ibanId(String ibanId) {
    this.ibanId = ibanId;
    return this;
  }

   /**
   * Get ibanId
   * @return ibanId
  **/
  @ApiModelProperty(value = "")
  public String getIbanId() {
    return ibanId;
  }

  public void setIbanId(String ibanId) {
    this.ibanId = ibanId;
  }

  public Payin ibanBic(String ibanBic) {
    this.ibanBic = ibanBic;
    return this;
  }

   /**
   * Get ibanBic
   * @return ibanBic
  **/
  @ApiModelProperty(value = "")
  public String getIbanBic() {
    return ibanBic;
  }

  public void setIbanBic(String ibanBic) {
    this.ibanBic = ibanBic;
  }

  public Payin ibanTxEndToEndId(String ibanTxEndToEndId) {
    this.ibanTxEndToEndId = ibanTxEndToEndId;
    return this;
  }

   /**
   * Get ibanTxEndToEndId
   * @return ibanTxEndToEndId
  **/
  @ApiModelProperty(value = "")
  public String getIbanTxEndToEndId() {
    return ibanTxEndToEndId;
  }

  public void setIbanTxEndToEndId(String ibanTxEndToEndId) {
    this.ibanTxEndToEndId = ibanTxEndToEndId;
  }

  public Payin ibanTxId(String ibanTxId) {
    this.ibanTxId = ibanTxId;
    return this;
  }

   /**
   * Get ibanTxId
   * @return ibanTxId
  **/
  @ApiModelProperty(value = "")
  public String getIbanTxId() {
    return ibanTxId;
  }

  public void setIbanTxId(String ibanTxId) {
    this.ibanTxId = ibanTxId;
  }

  public Payin refundAmount(String refundAmount) {
    this.refundAmount = refundAmount;
    return this;
  }

   /**
   * Get refundAmount
   * @return refundAmount
  **/
  @ApiModelProperty(value = "")
  public String getRefundAmount() {
    return refundAmount;
  }

  public void setRefundAmount(String refundAmount) {
    this.refundAmount = refundAmount;
  }

  public Payin totalRows(Integer totalRows) {
    this.totalRows = totalRows;
    return this;
  }

   /**
   * Get totalRows
   * @return totalRows
  **/
  @ApiModelProperty(value = "")
  public Integer getTotalRows() {
    return totalRows;
  }

  public void setTotalRows(Integer totalRows) {
    this.totalRows = totalRows;
  }

  public Payin forwardUrl(String forwardUrl) {
    this.forwardUrl = forwardUrl;
    return this;
  }

   /**
   * Get forwardUrl
   * @return forwardUrl
  **/
  @ApiModelProperty(value = "")
  public String getForwardUrl() {
    return forwardUrl;
  }

  public void setForwardUrl(String forwardUrl) {
    this.forwardUrl = forwardUrl;
  }

  public Payin payinDate(String payinDate) {
    this.payinDate = payinDate;
    return this;
  }

   /**
   * Date YYYY-MM-DD
   * @return payinDate
  **/
  @ApiModelProperty(value = "Date YYYY-MM-DD")
  public String getPayinDate() {
    return payinDate;
  }

  public void setPayinDate(String payinDate) {
    this.payinDate = payinDate;
  }

  public Payin mandateId(Integer mandateId) {
    this.mandateId = mandateId;
    return this;
  }

   /**
   * Get mandateId
   * @return mandateId
  **/
  @ApiModelProperty(value = "")
  public Integer getMandateId() {
    return mandateId;
  }

  public void setMandateId(Integer mandateId) {
    this.mandateId = mandateId;
  }

  public Payin creditorName(String creditorName) {
    this.creditorName = creditorName;
    return this;
  }

   /**
   * Get creditorName
   * @return creditorName
  **/
  @ApiModelProperty(value = "")
  public String getCreditorName() {
    return creditorName;
  }

  public void setCreditorName(String creditorName) {
    this.creditorName = creditorName;
  }

  public Payin creditorAddressLine(String creditorAddressLine) {
    this.creditorAddressLine = creditorAddressLine;
    return this;
  }

   /**
   * Get creditorAddressLine
   * @return creditorAddressLine
  **/
  @ApiModelProperty(value = "")
  public String getCreditorAddressLine() {
    return creditorAddressLine;
  }

  public void setCreditorAddressLine(String creditorAddressLine) {
    this.creditorAddressLine = creditorAddressLine;
  }

  public Payin creditorCountry(String creditorCountry) {
    this.creditorCountry = creditorCountry;
    return this;
  }

   /**
   * Get creditorCountry
   * @return creditorCountry
  **/
  @ApiModelProperty(value = "")
  public String getCreditorCountry() {
    return creditorCountry;
  }

  public void setCreditorCountry(String creditorCountry) {
    this.creditorCountry = creditorCountry;
  }

  public Payin creditorIban(String creditorIban) {
    this.creditorIban = creditorIban;
    return this;
  }

   /**
   * Get creditorIban
   * @return creditorIban
  **/
  @ApiModelProperty(value = "")
  public String getCreditorIban() {
    return creditorIban;
  }

  public void setCreditorIban(String creditorIban) {
    this.creditorIban = creditorIban;
  }

  public Payin creditorBIC(String creditorBIC) {
    this.creditorBIC = creditorBIC;
    return this;
  }

   /**
   * Get creditorBIC
   * @return creditorBIC
  **/
  @ApiModelProperty(value = "")
  public String getCreditorBIC() {
    return creditorBIC;
  }

  public void setCreditorBIC(String creditorBIC) {
    this.creditorBIC = creditorBIC;
  }

  public Payin virtualIbanId(Integer virtualIbanId) {
    this.virtualIbanId = virtualIbanId;
    return this;
  }

   /**
   * Get virtualIbanId
   * @return virtualIbanId
  **/
  @ApiModelProperty(value = "")
  public Integer getVirtualIbanId() {
    return virtualIbanId;
  }

  public void setVirtualIbanId(Integer virtualIbanId) {
    this.virtualIbanId = virtualIbanId;
  }

  public Payin virtualIbanReference(String virtualIbanReference) {
    this.virtualIbanReference = virtualIbanReference;
    return this;
  }

   /**
   * Get virtualIbanReference
   * @return virtualIbanReference
  **/
  @ApiModelProperty(value = "")
  public String getVirtualIbanReference() {
    return virtualIbanReference;
  }

  public void setVirtualIbanReference(String virtualIbanReference) {
    this.virtualIbanReference = virtualIbanReference;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Payin payin = (Payin) o;
    return Objects.equals(this.payinId, payin.payinId) &&
        Objects.equals(this.payinTag, payin.payinTag) &&
        Objects.equals(this.payinStatus, payin.payinStatus) &&
        Objects.equals(this.codeStatus, payin.codeStatus) &&
        Objects.equals(this.informationStatus, payin.informationStatus) &&
        Objects.equals(this.walletId, payin.walletId) &&
        Objects.equals(this.userId, payin.userId) &&
        Objects.equals(this.cartId, payin.cartId) &&
        Objects.equals(this.walletEventName, payin.walletEventName) &&
        Objects.equals(this.walletAlias, payin.walletAlias) &&
        Objects.equals(this.userFirstname, payin.userFirstname) &&
        Objects.equals(this.userLastname, payin.userLastname) &&
        Objects.equals(this.messageToUser, payin.messageToUser) &&
        Objects.equals(this.paymentMethodId, payin.paymentMethodId) &&
        Objects.equals(this.subtotalItems, payin.subtotalItems) &&
        Objects.equals(this.subtotalServices, payin.subtotalServices) &&
        Objects.equals(this.subtotalTax, payin.subtotalTax) &&
        Objects.equals(this.amount, payin.amount) &&
        Objects.equals(this.currency, payin.currency) &&
        Objects.equals(this.distributorFee, payin.distributorFee) &&
        Objects.equals(this.createdDate, payin.createdDate) &&
        Objects.equals(this.createdIp, payin.createdIp) &&
        Objects.equals(this.paymentHtml, payin.paymentHtml) &&
        Objects.equals(this.paymentLanguage, payin.paymentLanguage) &&
        Objects.equals(this.paymentPostUrl, payin.paymentPostUrl) &&
        Objects.equals(this.paymentPostDataUrl, payin.paymentPostDataUrl) &&
        Objects.equals(this.paymentAcceptedUrl, payin.paymentAcceptedUrl) &&
        Objects.equals(this.paymentWaitingUrl, payin.paymentWaitingUrl) &&
        Objects.equals(this.paymentRefusedUrl, payin.paymentRefusedUrl) &&
        Objects.equals(this.paymentCanceledUrl, payin.paymentCanceledUrl) &&
        Objects.equals(this.paymentExceptionUrl, payin.paymentExceptionUrl) &&
        Objects.equals(this.ibanFullname, payin.ibanFullname) &&
        Objects.equals(this.ibanId, payin.ibanId) &&
        Objects.equals(this.ibanBic, payin.ibanBic) &&
        Objects.equals(this.ibanTxEndToEndId, payin.ibanTxEndToEndId) &&
        Objects.equals(this.ibanTxId, payin.ibanTxId) &&
        Objects.equals(this.refundAmount, payin.refundAmount) &&
        Objects.equals(this.totalRows, payin.totalRows) &&
        Objects.equals(this.forwardUrl, payin.forwardUrl) &&
        Objects.equals(this.payinDate, payin.payinDate) &&
        Objects.equals(this.mandateId, payin.mandateId) &&
        Objects.equals(this.creditorName, payin.creditorName) &&
        Objects.equals(this.creditorAddressLine, payin.creditorAddressLine) &&
        Objects.equals(this.creditorCountry, payin.creditorCountry) &&
        Objects.equals(this.creditorIban, payin.creditorIban) &&
        Objects.equals(this.creditorBIC, payin.creditorBIC) &&
        Objects.equals(this.virtualIbanId, payin.virtualIbanId) &&
        Objects.equals(this.virtualIbanReference, payin.virtualIbanReference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(payinId, payinTag, payinStatus, codeStatus, informationStatus, walletId, userId, cartId, walletEventName, walletAlias, userFirstname, userLastname, messageToUser, paymentMethodId, subtotalItems, subtotalServices, subtotalTax, amount, currency, distributorFee, createdDate, createdIp, paymentHtml, paymentLanguage, paymentPostUrl, paymentPostDataUrl, paymentAcceptedUrl, paymentWaitingUrl, paymentRefusedUrl, paymentCanceledUrl, paymentExceptionUrl, ibanFullname, ibanId, ibanBic, ibanTxEndToEndId, ibanTxId, refundAmount, totalRows, forwardUrl, payinDate, mandateId, creditorName, creditorAddressLine, creditorCountry, creditorIban, creditorBIC, virtualIbanId, virtualIbanReference);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Payin {\n");
    
    sb.append("    payinId: ").append(toIndentedString(payinId)).append("\n");
    sb.append("    payinTag: ").append(toIndentedString(payinTag)).append("\n");
    sb.append("    payinStatus: ").append(toIndentedString(payinStatus)).append("\n");
    sb.append("    codeStatus: ").append(toIndentedString(codeStatus)).append("\n");
    sb.append("    informationStatus: ").append(toIndentedString(informationStatus)).append("\n");
    sb.append("    walletId: ").append(toIndentedString(walletId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    cartId: ").append(toIndentedString(cartId)).append("\n");
    sb.append("    walletEventName: ").append(toIndentedString(walletEventName)).append("\n");
    sb.append("    walletAlias: ").append(toIndentedString(walletAlias)).append("\n");
    sb.append("    userFirstname: ").append(toIndentedString(userFirstname)).append("\n");
    sb.append("    userLastname: ").append(toIndentedString(userLastname)).append("\n");
    sb.append("    messageToUser: ").append(toIndentedString(messageToUser)).append("\n");
    sb.append("    paymentMethodId: ").append(toIndentedString(paymentMethodId)).append("\n");
    sb.append("    subtotalItems: ").append(toIndentedString(subtotalItems)).append("\n");
    sb.append("    subtotalServices: ").append(toIndentedString(subtotalServices)).append("\n");
    sb.append("    subtotalTax: ").append(toIndentedString(subtotalTax)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    distributorFee: ").append(toIndentedString(distributorFee)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    createdIp: ").append(toIndentedString(createdIp)).append("\n");
    sb.append("    paymentHtml: ").append(toIndentedString(paymentHtml)).append("\n");
    sb.append("    paymentLanguage: ").append(toIndentedString(paymentLanguage)).append("\n");
    sb.append("    paymentPostUrl: ").append(toIndentedString(paymentPostUrl)).append("\n");
    sb.append("    paymentPostDataUrl: ").append(toIndentedString(paymentPostDataUrl)).append("\n");
    sb.append("    paymentAcceptedUrl: ").append(toIndentedString(paymentAcceptedUrl)).append("\n");
    sb.append("    paymentWaitingUrl: ").append(toIndentedString(paymentWaitingUrl)).append("\n");
    sb.append("    paymentRefusedUrl: ").append(toIndentedString(paymentRefusedUrl)).append("\n");
    sb.append("    paymentCanceledUrl: ").append(toIndentedString(paymentCanceledUrl)).append("\n");
    sb.append("    paymentExceptionUrl: ").append(toIndentedString(paymentExceptionUrl)).append("\n");
    sb.append("    ibanFullname: ").append(toIndentedString(ibanFullname)).append("\n");
    sb.append("    ibanId: ").append(toIndentedString(ibanId)).append("\n");
    sb.append("    ibanBic: ").append(toIndentedString(ibanBic)).append("\n");
    sb.append("    ibanTxEndToEndId: ").append(toIndentedString(ibanTxEndToEndId)).append("\n");
    sb.append("    ibanTxId: ").append(toIndentedString(ibanTxId)).append("\n");
    sb.append("    refundAmount: ").append(toIndentedString(refundAmount)).append("\n");
    sb.append("    totalRows: ").append(toIndentedString(totalRows)).append("\n");
    sb.append("    forwardUrl: ").append(toIndentedString(forwardUrl)).append("\n");
    sb.append("    payinDate: ").append(toIndentedString(payinDate)).append("\n");
    sb.append("    mandateId: ").append(toIndentedString(mandateId)).append("\n");
    sb.append("    creditorName: ").append(toIndentedString(creditorName)).append("\n");
    sb.append("    creditorAddressLine: ").append(toIndentedString(creditorAddressLine)).append("\n");
    sb.append("    creditorCountry: ").append(toIndentedString(creditorCountry)).append("\n");
    sb.append("    creditorIban: ").append(toIndentedString(creditorIban)).append("\n");
    sb.append("    creditorBIC: ").append(toIndentedString(creditorBIC)).append("\n");
    sb.append("    virtualIbanId: ").append(toIndentedString(virtualIbanId)).append("\n");
    sb.append("    virtualIbanReference: ").append(toIndentedString(virtualIbanReference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

