/*
 * Treezor
 * Treezor API.  more info [here](https://www.treezor.com). 
 *
 * OpenAPI spec version: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.treezor.sandbox.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Transaction
 */

public class Transaction {
  @SerializedName("transactionId")
  private Integer transactionId = null;

  @SerializedName("walletDebitId")
  private Integer walletDebitId = null;

  @SerializedName("walletCreditId")
  private Integer walletCreditId = null;

  @SerializedName("transactionType")
  private String transactionType = null;

  @SerializedName("foreignId")
  private Integer foreignId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("valueDate")
  private String valueDate = null;

  @SerializedName("executionDate")
  private String executionDate = null;

  @SerializedName("amount")
  private String amount = null;

  @SerializedName("walletDebitBalance")
  private String walletDebitBalance = null;

  @SerializedName("walletCreditBalance")
  private String walletCreditBalance = null;

  @SerializedName("currency")
  private String currency = null;

  @SerializedName("createdDate")
  private String createdDate = null;

  @SerializedName("totalRows")
  private Integer totalRows = null;

  public Transaction transactionId(Integer transactionId) {
    this.transactionId = transactionId;
    return this;
  }

   /**
   * Get transactionId
   * @return transactionId
  **/
  @ApiModelProperty(value = "")
  public Integer getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(Integer transactionId) {
    this.transactionId = transactionId;
  }

  public Transaction walletDebitId(Integer walletDebitId) {
    this.walletDebitId = walletDebitId;
    return this;
  }

   /**
   * Get walletDebitId
   * @return walletDebitId
  **/
  @ApiModelProperty(value = "")
  public Integer getWalletDebitId() {
    return walletDebitId;
  }

  public void setWalletDebitId(Integer walletDebitId) {
    this.walletDebitId = walletDebitId;
  }

  public Transaction walletCreditId(Integer walletCreditId) {
    this.walletCreditId = walletCreditId;
    return this;
  }

   /**
   * Get walletCreditId
   * @return walletCreditId
  **/
  @ApiModelProperty(value = "")
  public Integer getWalletCreditId() {
    return walletCreditId;
  }

  public void setWalletCreditId(Integer walletCreditId) {
    this.walletCreditId = walletCreditId;
  }

  public Transaction transactionType(String transactionType) {
    this.transactionType = transactionType;
    return this;
  }

   /**
   * Get transactionType
   * @return transactionType
  **/
  @ApiModelProperty(value = "")
  public String getTransactionType() {
    return transactionType;
  }

  public void setTransactionType(String transactionType) {
    this.transactionType = transactionType;
  }

  public Transaction foreignId(Integer foreignId) {
    this.foreignId = foreignId;
    return this;
  }

   /**
   * Get foreignId
   * @return foreignId
  **/
  @ApiModelProperty(value = "")
  public Integer getForeignId() {
    return foreignId;
  }

  public void setForeignId(Integer foreignId) {
    this.foreignId = foreignId;
  }

  public Transaction name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Transaction description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Transaction valueDate(String valueDate) {
    this.valueDate = valueDate;
    return this;
  }

   /**
   * Date YYYY-MM-DD
   * @return valueDate
  **/
  @ApiModelProperty(value = "Date YYYY-MM-DD")
  public String getValueDate() {
    return valueDate;
  }

  public void setValueDate(String valueDate) {
    this.valueDate = valueDate;
  }

  public Transaction executionDate(String executionDate) {
    this.executionDate = executionDate;
    return this;
  }

   /**
   * Date YYYY-MM-DD
   * @return executionDate
  **/
  @ApiModelProperty(value = "Date YYYY-MM-DD")
  public String getExecutionDate() {
    return executionDate;
  }

  public void setExecutionDate(String executionDate) {
    this.executionDate = executionDate;
  }

  public Transaction amount(String amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @ApiModelProperty(value = "")
  public String getAmount() {
    return amount;
  }

  public void setAmount(String amount) {
    this.amount = amount;
  }

  public Transaction walletDebitBalance(String walletDebitBalance) {
    this.walletDebitBalance = walletDebitBalance;
    return this;
  }

   /**
   * Get walletDebitBalance
   * @return walletDebitBalance
  **/
  @ApiModelProperty(value = "")
  public String getWalletDebitBalance() {
    return walletDebitBalance;
  }

  public void setWalletDebitBalance(String walletDebitBalance) {
    this.walletDebitBalance = walletDebitBalance;
  }

  public Transaction walletCreditBalance(String walletCreditBalance) {
    this.walletCreditBalance = walletCreditBalance;
    return this;
  }

   /**
   * Get walletCreditBalance
   * @return walletCreditBalance
  **/
  @ApiModelProperty(value = "")
  public String getWalletCreditBalance() {
    return walletCreditBalance;
  }

  public void setWalletCreditBalance(String walletCreditBalance) {
    this.walletCreditBalance = walletCreditBalance;
  }

  public Transaction currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @ApiModelProperty(value = "")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public Transaction createdDate(String createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Date YYYY-MM-DD HH:MM:SS
   * @return createdDate
  **/
  @ApiModelProperty(value = "Date YYYY-MM-DD HH:MM:SS")
  public String getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(String createdDate) {
    this.createdDate = createdDate;
  }

  public Transaction totalRows(Integer totalRows) {
    this.totalRows = totalRows;
    return this;
  }

   /**
   * Get totalRows
   * @return totalRows
  **/
  @ApiModelProperty(value = "")
  public Integer getTotalRows() {
    return totalRows;
  }

  public void setTotalRows(Integer totalRows) {
    this.totalRows = totalRows;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Transaction transaction = (Transaction) o;
    return Objects.equals(this.transactionId, transaction.transactionId) &&
        Objects.equals(this.walletDebitId, transaction.walletDebitId) &&
        Objects.equals(this.walletCreditId, transaction.walletCreditId) &&
        Objects.equals(this.transactionType, transaction.transactionType) &&
        Objects.equals(this.foreignId, transaction.foreignId) &&
        Objects.equals(this.name, transaction.name) &&
        Objects.equals(this.description, transaction.description) &&
        Objects.equals(this.valueDate, transaction.valueDate) &&
        Objects.equals(this.executionDate, transaction.executionDate) &&
        Objects.equals(this.amount, transaction.amount) &&
        Objects.equals(this.walletDebitBalance, transaction.walletDebitBalance) &&
        Objects.equals(this.walletCreditBalance, transaction.walletCreditBalance) &&
        Objects.equals(this.currency, transaction.currency) &&
        Objects.equals(this.createdDate, transaction.createdDate) &&
        Objects.equals(this.totalRows, transaction.totalRows);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionId, walletDebitId, walletCreditId, transactionType, foreignId, name, description, valueDate, executionDate, amount, walletDebitBalance, walletCreditBalance, currency, createdDate, totalRows);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Transaction {\n");
    
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    walletDebitId: ").append(toIndentedString(walletDebitId)).append("\n");
    sb.append("    walletCreditId: ").append(toIndentedString(walletCreditId)).append("\n");
    sb.append("    transactionType: ").append(toIndentedString(transactionType)).append("\n");
    sb.append("    foreignId: ").append(toIndentedString(foreignId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    valueDate: ").append(toIndentedString(valueDate)).append("\n");
    sb.append("    executionDate: ").append(toIndentedString(executionDate)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    walletDebitBalance: ").append(toIndentedString(walletDebitBalance)).append("\n");
    sb.append("    walletCreditBalance: ").append(toIndentedString(walletCreditBalance)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    totalRows: ").append(toIndentedString(totalRows)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

